﻿﻿using System.Collections.Generic;
using System.Linq;
using Logisfashion.LogisCore.Common.Seeds.Shared.Constants;
using Logisfashion.LogisCore.SharedBC.Model;
using Logisfashion.LogisCore.Seedwork;

namespace Logisfashion.LogisCore.Common.Seeds.Shared.Data
{
    public static class CommonSeed
    {
        public static Country[] GetCountries()
        {
            return new[]
            {
                new Country(020, "AND"),
                new Country(784, "ARE"),
                new Country(004, "AFG"),
                new Country(028, "ATG"),
                new Country(660, "AIA"),
                new Country(008, "ALB"),
                new Country(051, "ARM"),
                new Country(530, "ANT"),
                new Country(024, "AGO"),
                new Country(010, "ATA"),
                new Country(032, "ARG"),
                new Country(016, "ASM"),
                new Country(040, "AUT"),
                new Country(036, "AUS"),
                new Country(533, "ABW"),
                new Country(248, "ALA"),
                new Country(031, "AZE"),
                new Country(070, "BIH"),
                new Country(052, "BRB"),
                new Country(050, "BGD"),
                new Country(056, "BEL"),
                new Country(854, "BFA"),
                new Country(100, "BGR"),
                new Country(048, "BHR"),
                new Country(108, "BDI"),
                new Country(204, "BEN"),
                new Country(060, "BMU"),
                new Country(096, "BRN"),
                new Country(068, "BOL"),
                new Country(076, "BRA"),
                new Country(044, "BHS"),
                new Country(064, "BTN"),
                new Country(074, "BVT"),
                new Country(072, "BWA"),
                new Country(112, "BLR"),
                new Country(084, "BLZ"),
                new Country(124, "CAN"),
                new Country(166, "CCK"),
                new Country(180, "COD"),
                new Country(140, "CAF"),
                new Country(178, "COG"),
                new Country(756, "CHE"),
                new Country(384, "CIV"),
                new Country(184, "COK"),
                new Country(152, "CHL"),
                new Country(120, "CMR"),
                new Country(156, "CHN"),
                new Country(170, "COL"),
                new Country(188, "CRI"),
                new Country(891, "SRB"),
                new Country(192, "CUB"),
                new Country(132, "CPV"),
                new Country(162, "CXR"),
                new Country(196, "CYP"),
                new Country(203, "CZE"),
                new Country(276, "DEU"),
                new Country(262, "DJI"),
                new Country(208, "DNK"),
                new Country(212, "DMA"),
                new Country(214, "DOM"),
                new Country(012, "DZA"),
                new Country(218, "ECU"),
                new Country(233, "EST"),
                new Country(818, "EGY"),
                new Country(732, "ESH"),
                new Country(232, "ERI"),
                new Country(724, "ESP"),
                new Country(231, "ETH"),
                new Country(246, "FIN"),
                new Country(242, "FJI"),
                new Country(238, "FLK"),
                new Country(583, "FSM"),
                new Country(234, "FRO"),
                new Country(250, "FRA"),
                new Country(266, "GAB"),
                new Country(826, "GBR"),
                new Country(308, "GRD"),
                new Country(268, "GEO"),
                new Country(254, "GUF"),
                new Country(288, "GHA"),
                new Country(292, "GIB"),
                new Country(304, "GRL"),
                new Country(270, "GMB"),
                new Country(324, "GIN"),
                new Country(312, "GLP"),
                new Country(226, "GNQ"),
                new Country(300, "GRC"),
                new Country(239, "SGS"),
                new Country(320, "GTM"),
                new Country(316, "GUM"),
                new Country(624, "GNB"),
                new Country(328, "GUY"),
                new Country(344, "HKG"),
                new Country(334, "HMD"),
                new Country(340, "HND"),
                new Country(191, "HRV"),
                new Country(332, "HTI"),
                new Country(348, "HUN"),
                new Country(360, "IDN"),
                new Country(372, "IRL"),
                new Country(376, "ISR"),
                new Country(356, "IND"),
                new Country(086, "IOT"),
                new Country(368, "IRQ"),
                new Country(364, "IRN"),
                new Country(352, "ISL"),
                new Country(380, "ITA"),
                new Country(388, "JAM"),
                new Country(400, "JOR"),
                new Country(392, "JPN"),
                new Country(404, "KEN"),
                new Country(417, "KGZ"),
                new Country(116, "KHM"),
                new Country(296, "KIR"),
                new Country(174, "COM"),
                new Country(659, "KNA"),
                new Country(408, "PRK"),
                new Country(410, "KOR"),
                new Country(414, "KWT"),
                new Country(136, "CYM"),
                new Country(398, "KAZ"),
                new Country(418, "LAO"),
                new Country(422, "LBN"),
                new Country(662, "LCA"),
                new Country(438, "LIE"),
                new Country(144, "LKA"),
                new Country(430, "LBR"),
                new Country(426, "LSO"),
                new Country(440, "LTU"),
                new Country(442, "LUX"),
                new Country(428, "LVA"),
                new Country(434, "LBY"),
                new Country(504, "MAR"),
                new Country(492, "MCO"),
                new Country(498, "MDA"),
                new Country(450, "MDG"),
                new Country(584, "MHL"),
                new Country(807, "MKD"),
                new Country(466, "MLI"),
                new Country(104, "MMR"),
                new Country(496, "MNG"),
                new Country(446, "MAC"),
                new Country(580, "MNP"),
                new Country(474, "MTQ"),
                new Country(478, "MRT"),
                new Country(500, "MSR"),
                new Country(470, "MLT"),
                new Country(480, "MUS"),
                new Country(462, "MDV"),
                new Country(454, "MWI"),
                new Country(484, "MEX"),
                new Country(458, "MYS"),
                new Country(508, "MOZ"),
                new Country(516, "NAM"),
                new Country(540, "NCL"),
                new Country(562, "NER"),
                new Country(574, "NFK"),
                new Country(566, "NGA"),
                new Country(558, "NIC"),
                new Country(528, "NLD"),
                new Country(578, "NOR"),
                new Country(524, "NPL"),
                new Country(520, "NRU"),
                new Country(570, "NIU"),
                new Country(554, "NZL"),
                new Country(512, "OMN"),
                new Country(591, "PAN"),
                new Country(604, "PER"),
                new Country(258, "PYF"),
                new Country(598, "PNG"),
                new Country(608, "PHL"),
                new Country(586, "PAK"),
                new Country(616, "POL"),
                new Country(666, "SPM"),
                new Country(612, "PCN"),
                new Country(630, "PRI"),
                new Country(275, "PSE"),
                new Country(620, "PRT"),
                new Country(585, "PLW"),
                new Country(600, "PRY"),
                new Country(634, "QAT"),
                new Country(638, "REU"),
                new Country(642, "ROU"),
                new Country(643, "RUS"),
                new Country(646, "RWA"),
                new Country(682, "SAU"),
                new Country(090, "SLB"),
                new Country(690, "SYC"),
                new Country(736, "SDN"),
                new Country(752, "SWE"),
                new Country(702, "SGP"),
                new Country(654, "SHN"),
                new Country(705, "SVN"),
                new Country(744, "SJM"),
                new Country(703, "SVK"),
                new Country(694, "SLE"),
                new Country(674, "SMR"),
                new Country(686, "SEN"),
                new Country(706, "SOM"),
                new Country(740, "SUR"),
                new Country(678, "STP"),
                new Country(222, "SLV"),
                new Country(760, "SYR"),
                new Country(748, "SWZ"),
                new Country(796, "TCA"),
                new Country(148, "TCD"),
                new Country(260, "ATF"),
                new Country(768, "TGO"),
                new Country(764, "THA"),
                new Country(762, "TJK"),
                new Country(772, "TKL"),
                new Country(626, "TLS"),
                new Country(795, "TKM"),
                new Country(788, "TUN"),
                new Country(776, "TON"),
                new Country(792, "TUR"),
                new Country(780, "TTO"),
                new Country(798, "TUV"),
                new Country(158, "TWN"),
                new Country(834, "TZA"),
                new Country(804, "UKR"),
                new Country(800, "UGA"),
                new Country(581, "UMI"),
                new Country(840, "USA"),
                new Country(858, "URY"),
                new Country(860, "UZB"),
                new Country(336, "VAT"),
                new Country(670, "VCT"),
                new Country(862, "VEN"),
                new Country(092, "VGB"),
                new Country(850, "VIR"),
                new Country(704, "VNM"),
                new Country(548, "VUT"),
                new Country(876, "WLF"),
                new Country(882, "WSM"),
                new Country(887, "YEM"),
                new Country(175, "MYT"),
                new Country(710, "ZAF"),
                new Country(894, "ZMB"),
                new Country(716, "ZWE")









            };
        }

        public static CountryTranslation[] GetCountryTranslations()
        {
            return new[]
            {
                // Spanish
                new CountryTranslation(020, "es", true, "[ES]ANDORRA"),
                new CountryTranslation(784, "es", true, "[ES]UNITED ARAB EMIRATES"),
                new CountryTranslation(004, "es", true, "[ES]AFGHANISTAN"),
                new CountryTranslation(028, "es", true, "[ES]ANTIGUA AND BARBUDA"),
                new CountryTranslation(660, "es", true, "[ES]ANGUILLA"),
                new CountryTranslation(008, "es", true, "[ES]ALBANIA"),
                new CountryTranslation(051, "es", true, "[ES]ARMENIA"),
                new CountryTranslation(530, "es", true, "[ES]NETHERLANDS ANTILLES"),
                new CountryTranslation(024, "es", true, "[ES]ANGOLA"),
                new CountryTranslation(010, "es", true, "[ES]ANTARCTICA"),
                new CountryTranslation(032, "es", true, "[ES]ARGENTINA"),
                new CountryTranslation(016, "es", true, "[ES]AMERICAN SAMOA"),
                new CountryTranslation(040, "es", true, "[ES]AUSTRIA"),
                new CountryTranslation(036, "es", true, "[ES]AUSTRALIA"),
                new CountryTranslation(533, "es", true, "[ES]ARUBA"),
                new CountryTranslation(248, "es", true, "[ES]AALAND ISLANDS"),
                new CountryTranslation(031, "es", true, "[ES]AZERBAIJAN"),
                new CountryTranslation(070, "es", true, "[ES]BOSNIA AND HERZEGOWINA"),
                new CountryTranslation(052, "es", true, "[ES]BARBADOS"),
                new CountryTranslation(050, "es", true, "[ES]BANGLADESH"),
                new CountryTranslation(056, "es", true, "[ES]BELGIUM"),
                new CountryTranslation(854, "es", true, "[ES]BURKINA FASO"),
                new CountryTranslation(100, "es", true, "[ES]BULGARIA"),
                new CountryTranslation(048, "es", true, "[ES]BAHRAIN"),
                new CountryTranslation(108, "es", true, "[ES]BURUNDI"),
                new CountryTranslation(204, "es", true, "[ES]BENIN"),
                new CountryTranslation(060, "es", true, "[ES]BERMUDA"),
                new CountryTranslation(096, "es", true, "[ES]BRUNEI DARUSSALAM"),
                new CountryTranslation(068, "es", true, "[ES]BOLIVIA"),
                new CountryTranslation(076, "es", true, "[ES]BRAZIL"),
                new CountryTranslation(044, "es", true, "[ES]BAHAMAS"),
                new CountryTranslation(064, "es", true, "[ES]BHUTAN"),
                new CountryTranslation(074, "es", true, "[ES]BOUVET ISLAND"),
                new CountryTranslation(072, "es", true, "[ES]BOTSWANA"),
                new CountryTranslation(112, "es", true, "[ES]BELARUS"),
                new CountryTranslation(084, "es", true, "[ES]BELIZE"),
                new CountryTranslation(124, "es", true, "[ES]CANADA"),
                new CountryTranslation(166, "es", true, "[ES]COCOS (KEELING) ISLANDS"),
                new CountryTranslation(180, "es", true, "[ES]CONGO, Democratic Republic of (was Zaire)"),
                new CountryTranslation(140, "es", true, "[ES]CENTRAL AFRICAN REPUBLIC"),
                new CountryTranslation(178, "es", true, "[ES]CONGO, Republic of"),
                new CountryTranslation(756, "es", true, "[ES]SWITZERLAND"),
                new CountryTranslation(384, "es", true, "[ES]COTE D'IVOIRE"),
                new CountryTranslation(184, "es", true, "[ES]COOK ISLANDS"),
                new CountryTranslation(152, "es", true, "[ES]CHILE"),
                new CountryTranslation(120, "es", true, "[ES]CAMEROON"),
                new CountryTranslation(156, "es", true, "[ES]CHINA"),
                new CountryTranslation(170, "es", true, "[ES]COLOMBIA"),
                new CountryTranslation(188, "es", true, "[ES]COSTA RICA"),
                new CountryTranslation(891, "es", true, "[ES]SERBIA AND MONTENEGRO"),
                new CountryTranslation(192, "es", true, "[ES]CUBA"),
                new CountryTranslation(132, "es", true, "[ES]CAPE VERDE"),
                new CountryTranslation(162, "es", true, "[ES]CHRISTMAS ISLAND"),
                new CountryTranslation(196, "es", true, "[ES]CYPRUS"),
                new CountryTranslation(203, "es", true, "[ES]CZECH REPUBLIC"),
                new CountryTranslation(276, "es", true, "[ES]GERMANY"),
                new CountryTranslation(262, "es", true, "[ES]DJIBOUTI"),
                new CountryTranslation(208, "es", true, "[ES]DENMARK"),
                new CountryTranslation(212, "es", true, "[ES]DOMINICA"),
                new CountryTranslation(214, "es", true, "[ES]DOMINICAN REPUBLIC"),
                new CountryTranslation(012, "es", true, "[ES]ALGERIA"),
                new CountryTranslation(218, "es", true, "[ES]ECUADOR"),
                new CountryTranslation(233, "es", true, "[ES]ESTONIA"),
                new CountryTranslation(818, "es", true, "[ES]EGYPT"),
                new CountryTranslation(732, "es", true, "[ES]WESTERN SAHARA"),
                new CountryTranslation(232, "es", true, "[ES]ERITREA"),
                new CountryTranslation(724, "es", true, "[ES]SPAIN"),
                new CountryTranslation(231, "es", true, "[ES]ETHIOPIA"),
                new CountryTranslation(246, "es", true, "[ES]FINLAND"),
                new CountryTranslation(242, "es", true, "[ES]FIJI"),
                new CountryTranslation(238, "es", true, "[ES]FALKLAND ISLANDS (MALVINAS)"),
                new CountryTranslation(583, "es", true, "[ES]MICRONESIA, FEDERATED STATES OF"),
                new CountryTranslation(234, "es", true, "[ES]FAROE ISLANDS"),
                new CountryTranslation(250, "es", true, "[ES]FRANCE"),
                new CountryTranslation(266, "es", true, "[ES]GABON"),
                new CountryTranslation(826, "es", true, "[ES]UNITED KINGDOM"),
                new CountryTranslation(308, "es", true, "[ES]GRENADA"),
                new CountryTranslation(268, "es", true, "[ES]GEORGIA"),
                new CountryTranslation(254, "es", true, "[ES]FRENCH GUIANA"),
                new CountryTranslation(288, "es", true, "[ES]GHANA"),
                new CountryTranslation(292, "es", true, "[ES]GIBRALTAR"),
                new CountryTranslation(304, "es", true, "[ES]GREENLAND"),
                new CountryTranslation(270, "es", true, "[ES]GAMBIA"),
                new CountryTranslation(324, "es", true, "[ES]GUINEA"),
                new CountryTranslation(312, "es", true, "[ES]GUADELOUPE"),
                new CountryTranslation(226, "es", true, "[ES]EQUATORIAL GUINEA"),
                new CountryTranslation(300, "es", true, "[ES]GREECE"),
                new CountryTranslation(239, "es", true, "[ES]SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS"),
                new CountryTranslation(320, "es", true, "[ES]GUATEMALA"),
                new CountryTranslation(316, "es", true, "[ES]GUAM"),
                new CountryTranslation(624, "es", true, "[ES]GUINEA-BISSAU"),
                new CountryTranslation(328, "es", true, "[ES]GUYANA"),
                new CountryTranslation(344, "es", true, "[ES]HONG KONG"),
                new CountryTranslation(334, "es", true, "[ES]HEARD AND MC DONALD ISLANDS"),
                new CountryTranslation(340, "es", true, "[ES]HONDURAS"),
                new CountryTranslation(191, "es", true, "[ES]CROATIA"),
                new CountryTranslation(332, "es", true, "[ES]HAITI"),
                new CountryTranslation(348, "es", true, "[ES]HUNGARY"),
                new CountryTranslation(360, "es", true, "[ES]INDONESIA"),
                new CountryTranslation(372, "es", true, "[ES]IRELAND"),
                new CountryTranslation(376, "es", true, "[ES]ISRAEL"),
                new CountryTranslation(356, "es", true, "[ES]INDIA"),
                new CountryTranslation(086, "es", true, "[ES]BRITISH INDIAN OCEAN TERRITORY"),
                new CountryTranslation(368, "es", true, "[ES]IRAQ"),
                new CountryTranslation(364, "es", true, "[ES]IRAN (ISLAMIC REPUBLIC OF)"),
                new CountryTranslation(352, "es", true, "[ES]ICELAND"),
                new CountryTranslation(380, "es", true, "[ES]ITALY"),
                new CountryTranslation(388, "es", true, "[ES]JAMAICA"),
                new CountryTranslation(400, "es", true, "[ES]JORDAN"),
                new CountryTranslation(392, "es", true, "[ES]JAPAN"),
                new CountryTranslation(404, "es", true, "[ES]KENYA"),
                new CountryTranslation(417, "es", true, "[ES]KYRGYZSTAN"),
                new CountryTranslation(116, "es", true, "[ES]CAMBODIA"),
                new CountryTranslation(296, "es", true, "[ES]KIRIBATI"),
                new CountryTranslation(174, "es", true, "[ES]COMOROS"),
                new CountryTranslation(659, "es", true, "[ES]SAINT KITTS AND NEVIS"),
                new CountryTranslation(408, "es", true, "[ES]KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF"),
                new CountryTranslation(410, "es", true, "[ES]KOREA, REPUBLIC OF"),
                new CountryTranslation(414, "es", true, "[ES]KUWAIT"),
                new CountryTranslation(136, "es", true, "[ES]CAYMAN ISLANDS"),
                new CountryTranslation(398, "es", true, "[ES]KAZAKHSTAN"),
                new CountryTranslation(418, "es", true, "[ES]LAO PEOPLE'S DEMOCRATIC REPUBLIC"),
                new CountryTranslation(422, "es", true, "[ES]LEBANON"),
                new CountryTranslation(662, "es", true, "[ES]SAINT LUCIA"),
                new CountryTranslation(438, "es", true, "[ES]LIECHTENSTEIN"),
                new CountryTranslation(144, "es", true, "[ES]SRI LANKA"),
                new CountryTranslation(430, "es", true, "[ES]LIBERIA"),
                new CountryTranslation(426, "es", true, "[ES]LESOTHO"),
                new CountryTranslation(440, "es", true, "[ES]LITHUANIA"),
                new CountryTranslation(442, "es", true, "[ES]LUXEMBOURG"),
                new CountryTranslation(428, "es", true, "[ES]LATVIA"),
                new CountryTranslation(434, "es", true, "[ES]LIBYAN ARAB JAMAHIRIYA"),
                new CountryTranslation(504, "es", true, "[ES]MOROCCO"),
                new CountryTranslation(492, "es", true, "[ES]MONACO"),
                new CountryTranslation(498, "es", true, "[ES]MOLDOVA, REPUBLIC OF"),
                new CountryTranslation(450, "es", true, "[ES]MADAGASCAR"),
                new CountryTranslation(584, "es", true, "[ES]MARSHALL ISLANDS"),
                new CountryTranslation(807, "es", true, "[ES]MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF"),
                new CountryTranslation(466, "es", true, "[ES]MALI"),
                new CountryTranslation(104, "es", true, "[ES]MYANMAR"),
                new CountryTranslation(496, "es", true, "[ES]MONGOLIA"),
                new CountryTranslation(446, "es", true, "[ES]MACAU"),
                new CountryTranslation(580, "es", true, "[ES]NORTHERN MARIANA ISLANDS"),
                new CountryTranslation(474, "es", true, "[ES]MARTINIQUE"),
                new CountryTranslation(478, "es", true, "[ES]MAURITANIA"),
                new CountryTranslation(500, "es", true, "[ES]MONTSERRAT"),
                new CountryTranslation(470, "es", true, "[ES]MALTA"),
                new CountryTranslation(480, "es", true, "[ES]MAURITIUS"),
                new CountryTranslation(462, "es", true, "[ES]MALDIVES"),
                new CountryTranslation(454, "es", true, "[ES]MALAWI"),
                new CountryTranslation(484, "es", true, "[ES]MEXICO"),
                new CountryTranslation(458, "es", true, "[ES]MALAYSIA"),
                new CountryTranslation(508, "es", true, "[ES]MOZAMBIQUE"),
                new CountryTranslation(516, "es", true, "[ES]NAMIBIA"),
                new CountryTranslation(540, "es", true, "[ES]NEW CALEDONIA"),
                new CountryTranslation(562, "es", true, "[ES]NIGER"),
                new CountryTranslation(574, "es", true, "[ES]NORFOLK ISLAND"),
                new CountryTranslation(566, "es", true, "[ES]NIGERIA"),
                new CountryTranslation(558, "es", true, "[ES]NICARAGUA"),
                new CountryTranslation(528, "es", true, "[ES]NETHERLANDS"),
                new CountryTranslation(578, "es", true, "[ES]NORWAY"),
                new CountryTranslation(524, "es", true, "[ES]NEPAL"),
                new CountryTranslation(520, "es", true, "[ES]NAURU"),
                new CountryTranslation(570, "es", true, "[ES]NIUE"),
                new CountryTranslation(554, "es", true, "[ES]NEW ZEALAND"),
                new CountryTranslation(512, "es", true, "[ES]OMAN"),
                new CountryTranslation(591, "es", true, "[ES]PANAMA"),
                new CountryTranslation(604, "es", true, "[ES]PERU"),
                new CountryTranslation(258, "es", true, "[ES]FRENCH POLYNESIA"),
                new CountryTranslation(598, "es", true, "[ES]PAPUA NEW GUINEA"),
                new CountryTranslation(608, "es", true, "[ES]PHILIPPINES"),
                new CountryTranslation(586, "es", true, "[ES]PAKISTAN"),
                new CountryTranslation(616, "es", true, "[ES]POLAND"),
                new CountryTranslation(666, "es", true, "[ES]SAINT PIERRE AND MIQUELON"),
                new CountryTranslation(612, "es", true, "[ES]PITCAIRN"),
                new CountryTranslation(630, "es", true, "[ES]PUERTO RICO"),
                new CountryTranslation(275, "es", true, "[ES]PALESTINIAN TERRITORY, Occupied"),
                new CountryTranslation(620, "es", true, "[ES]PORTUGAL"),
                new CountryTranslation(585, "es", true, "[ES]PALAU"),
                new CountryTranslation(600, "es", true, "[ES]PARAGUAY"),
                new CountryTranslation(634, "es", true, "[ES]QATAR"),
                new CountryTranslation(638, "es", true, "[ES]REUNION"),
                new CountryTranslation(642, "es", true, "[ES]ROMANIA"),
                new CountryTranslation(643, "es", true, "[ES]RUSSIAN FEDERATION"),
                new CountryTranslation(646, "es", true, "[ES]RWANDA"),
                new CountryTranslation(682, "es", true, "[ES]SAUDI ARABIA"),
                new CountryTranslation(090, "es", true, "[ES]SOLOMON ISLANDS"),
                new CountryTranslation(690, "es", true, "[ES]SEYCHELLES"),
                new CountryTranslation(736, "es", true, "[ES]SUDAN"),
                new CountryTranslation(752, "es", true, "[ES]SWEDEN"),
                new CountryTranslation(702, "es", true, "[ES]SINGAPORE"),
                new CountryTranslation(654, "es", true, "[ES]SAINT HELENA"),
                new CountryTranslation(705, "es", true, "[ES]SLOVENIA"),
                new CountryTranslation(744, "es", true, "[ES]SVALBARD AND JAN MAYEN ISLANDS"),
                new CountryTranslation(703, "es", true, "[ES]SLOVAKIA"),
                new CountryTranslation(694, "es", true, "[ES]SIERRA LEONE"),
                new CountryTranslation(674, "es", true, "[ES]SAN MARINO"),
                new CountryTranslation(686, "es", true, "[ES]SENEGAL"),
                new CountryTranslation(706, "es", true, "[ES]SOMALIA"),
                new CountryTranslation(740, "es", true, "[ES]SURINAME"),
                new CountryTranslation(678, "es", true, "[ES]SAO TOME AND PRINCIPE"),
                new CountryTranslation(222, "es", true, "[ES]EL SALVADOR"),
                new CountryTranslation(760, "es", true, "[ES]SYRIAN ARAB REPUBLIC"),
                new CountryTranslation(748, "es", true, "[ES]SWAZILAND"),
                new CountryTranslation(796, "es", true, "[ES]TURKS AND CAICOS ISLANDS"),
                new CountryTranslation(148, "es", true, "[ES]CHAD"),
                new CountryTranslation(260, "es", true, "[ES]FRENCH SOUTHERN TERRITORIES"),
                new CountryTranslation(768, "es", true, "[ES]TOGO"),
                new CountryTranslation(764, "es", true, "[ES]THAILAND"),
                new CountryTranslation(762, "es", true, "[ES]TAJIKISTAN"),
                new CountryTranslation(772, "es", true, "[ES]TOKELAU"),
                new CountryTranslation(626, "es", true, "[ES]TIMOR-LESTE"),
                new CountryTranslation(795, "es", true, "[ES]TURKMENISTAN"),
                new CountryTranslation(788, "es", true, "[ES]TUNISIA"),
                new CountryTranslation(776, "es", true, "[ES]TONGA"),
                new CountryTranslation(792, "es", true, "[ES]TURKEY"),
                new CountryTranslation(780, "es", true, "[ES]TRINIDAD AND TOBAGO"),
                new CountryTranslation(798, "es", true, "[ES]TUVALU"),
                new CountryTranslation(158, "es", true, "[ES]TAIWAN"),
                new CountryTranslation(834, "es", true, "[ES]TANZANIA, UNITED REPUBLIC OF"),
                new CountryTranslation(804, "es", true, "[ES]UKRAINE"),
                new CountryTranslation(800, "es", true, "[ES]UGANDA"),
                new CountryTranslation(581, "es", true, "[ES]UNITED STATES MINOR OUTLYING ISLANDS"),
                new CountryTranslation(840, "es", true, "[ES]UNITED STATES"),
                new CountryTranslation(858, "es", true, "[ES]URUGUAY"),
                new CountryTranslation(860, "es", true, "[ES]UZBEKISTAN"),
                new CountryTranslation(336, "es", true, "[ES]VATICAN CITY STATE (HOLY SEE)"),
                new CountryTranslation(670, "es", true, "[ES]SAINT VINCENT AND THE GRENADINES"),
                new CountryTranslation(862, "es", true, "[ES]VENEZUELA"),
                new CountryTranslation(092, "es", true, "[ES]VIRGIN ISLANDS (BRITISH)"),
                new CountryTranslation(850, "es", true, "[ES]VIRGIN ISLANDS (U.S.)"),
                new CountryTranslation(704, "es", true, "[ES]VIETNAM"),
                new CountryTranslation(548, "es", true, "[ES]VANUATU"),
                new CountryTranslation(876, "es", true, "[ES]WALLIS AND FUTUNA ISLANDS"),
                new CountryTranslation(882, "es", true, "[ES]SAMOA"),
                new CountryTranslation(887, "es", true, "[ES]YEMEN"),
                new CountryTranslation(175, "es", true, "[ES]MAYOTTE"),
                new CountryTranslation(710, "es", true, "[ES]SOUTH AFRICA"),
                new CountryTranslation(894, "es", true, "[ES]ZAMBIA"),
                new CountryTranslation(716, "es", true, "[ES]ZIMBABWE"),










                // English
                new CountryTranslation(020, "en", false, "ANDORRA"),
                new CountryTranslation(784, "en", false, "UNITED ARAB EMIRATES"),
                new CountryTranslation(004, "en", false, "AFGHANISTAN"),
                new CountryTranslation(028, "en", false, "ANTIGUA AND BARBUDA"),
                new CountryTranslation(660, "en", false, "ANGUILLA"),
                new CountryTranslation(008, "en", false, "ALBANIA"),
                new CountryTranslation(051, "en", false, "ARMENIA"),
                new CountryTranslation(530, "en", false, "NETHERLANDS ANTILLES"),
                new CountryTranslation(024, "en", false, "ANGOLA"),
                new CountryTranslation(010, "en", false, "ANTARCTICA"),
                new CountryTranslation(032, "en", false, "ARGENTINA"),
                new CountryTranslation(016, "en", false, "AMERICAN SAMOA"),
                new CountryTranslation(040, "en", false, "AUSTRIA"),
                new CountryTranslation(036, "en", false, "AUSTRALIA"),
                new CountryTranslation(533, "en", false, "ARUBA"),
                new CountryTranslation(248, "en", false, "AALAND ISLANDS"),
                new CountryTranslation(031, "en", false, "AZERBAIJAN"),
                new CountryTranslation(070, "en", false, "BOSNIA AND HERZEGOWINA"),
                new CountryTranslation(052, "en", false, "BARBADOS"),
                new CountryTranslation(050, "en", false, "BANGLADESH"),
                new CountryTranslation(056, "en", false, "BELGIUM"),
                new CountryTranslation(854, "en", false, "BURKINA FASO"),
                new CountryTranslation(100, "en", false, "BULGARIA"),
                new CountryTranslation(048, "en", false, "BAHRAIN"),
                new CountryTranslation(108, "en", false, "BURUNDI"),
                new CountryTranslation(204, "en", false, "BENIN"),
                new CountryTranslation(060, "en", false, "BERMUDA"),
                new CountryTranslation(096, "en", false, "BRUNEI DARUSSALAM"),
                new CountryTranslation(068, "en", false, "BOLIVIA"),
                new CountryTranslation(076, "en", false, "BRAZIL"),
                new CountryTranslation(044, "en", false, "BAHAMAS"),
                new CountryTranslation(064, "en", false, "BHUTAN"),
                new CountryTranslation(074, "en", false, "BOUVET ISLAND"),
                new CountryTranslation(072, "en", false, "BOTSWANA"),
                new CountryTranslation(112, "en", false, "BELARUS"),
                new CountryTranslation(084, "en", false, "BELIZE"),
                new CountryTranslation(124, "en", false, "CANADA"),
                new CountryTranslation(166, "en", false, "COCOS (KEELING) ISLANDS"),
                new CountryTranslation(180, "en", false, "CONGO, Democratic Republic of (was Zaire)"),
                new CountryTranslation(140, "en", false, "CENTRAL AFRICAN REPUBLIC"),
                new CountryTranslation(178, "en", false, "CONGO, Republic of"),
                new CountryTranslation(756, "en", false, "SWITZERLAND"),
                new CountryTranslation(384, "en", false, "COTE D'IVOIRE"),
                new CountryTranslation(184, "en", false, "COOK ISLANDS"),
                new CountryTranslation(152, "en", false, "CHILE"),
                new CountryTranslation(120, "en", false, "CAMEROON"),
                new CountryTranslation(156, "en", false, "CHINA"),
                new CountryTranslation(170, "en", false, "COLOMBIA"),
                new CountryTranslation(188, "en", false, "COSTA RICA"),
                new CountryTranslation(891, "en", false, "SERBIA AND MONTENEGRO"),
                new CountryTranslation(192, "en", false, "CUBA"),
                new CountryTranslation(132, "en", false, "CAPE VERDE"),
                new CountryTranslation(162, "en", false, "CHRISTMAS ISLAND"),
                new CountryTranslation(196, "en", false, "CYPRUS"),
                new CountryTranslation(203, "en", false, "CZECH REPUBLIC"),
                new CountryTranslation(276, "en", false, "GERMANY"),
                new CountryTranslation(262, "en", false, "DJIBOUTI"),
                new CountryTranslation(208, "en", false, "DENMARK"),
                new CountryTranslation(212, "en", false, "DOMINICA"),
                new CountryTranslation(214, "en", false, "DOMINICAN REPUBLIC"),
                new CountryTranslation(012, "en", false, "ALGERIA"),
                new CountryTranslation(218, "en", false, "ECUADOR"),
                new CountryTranslation(233, "en", false, "ESTONIA"),
                new CountryTranslation(818, "en", false, "EGYPT"),
                new CountryTranslation(732, "en", false, "WESTERN SAHARA"),
                new CountryTranslation(232, "en", false, "ERITREA"),
                new CountryTranslation(724, "en", false, "SPAIN"),
                new CountryTranslation(231, "en", false, "ETHIOPIA"),
                new CountryTranslation(246, "en", false, "FINLAND"),
                new CountryTranslation(242, "en", false, "FIJI"),
                new CountryTranslation(238, "en", false, "FALKLAND ISLANDS (MALVINAS)"),
                new CountryTranslation(583, "en", false, "MICRONESIA, FEDERATED STATES OF"),
                new CountryTranslation(234, "en", false, "FAROE ISLANDS"),
                new CountryTranslation(250, "en", false, "FRANCE"),
                new CountryTranslation(266, "en", false, "GABON"),
                new CountryTranslation(826, "en", false, "UNITED KINGDOM"),
                new CountryTranslation(308, "en", false, "GRENADA"),
                new CountryTranslation(268, "en", false, "GEORGIA"),
                new CountryTranslation(254, "en", false, "FRENCH GUIANA"),
                new CountryTranslation(288, "en", false, "GHANA"),
                new CountryTranslation(292, "en", false, "GIBRALTAR"),
                new CountryTranslation(304, "en", false, "GREENLAND"),
                new CountryTranslation(270, "en", false, "GAMBIA"),
                new CountryTranslation(324, "en", false, "GUINEA"),
                new CountryTranslation(312, "en", false, "GUADELOUPE"),
                new CountryTranslation(226, "en", false, "EQUATORIAL GUINEA"),
                new CountryTranslation(300, "en", false, "GREECE"),
                new CountryTranslation(239, "en", false, "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS"),
                new CountryTranslation(320, "en", false, "GUATEMALA"),
                new CountryTranslation(316, "en", false, "GUAM"),
                new CountryTranslation(624, "en", false, "GUINEA-BISSAU"),
                new CountryTranslation(328, "en", false, "GUYANA"),
                new CountryTranslation(344, "en", false, "HONG KONG"),
                new CountryTranslation(334, "en", false, "HEARD AND MC DONALD ISLANDS"),
                new CountryTranslation(340, "en", false, "HONDURAS"),
                new CountryTranslation(191, "en", false, "CROATIA"),
                new CountryTranslation(332, "en", false, "HAITI"),
                new CountryTranslation(348, "en", false, "HUNGARY"),
                new CountryTranslation(360, "en", false, "INDONESIA"),
                new CountryTranslation(372, "en", false, "IRELAND"),
                new CountryTranslation(376, "en", false, "ISRAEL"),
                new CountryTranslation(356, "en", false, "INDIA"),
                new CountryTranslation(086, "en", false, "BRITISH INDIAN OCEAN TERRITORY"),
                new CountryTranslation(368, "en", false, "IRAQ"),
                new CountryTranslation(364, "en", false, "IRAN (ISLAMIC REPUBLIC OF)"),
                new CountryTranslation(352, "en", false, "ICELAND"),
                new CountryTranslation(380, "en", false, "ITALY"),
                new CountryTranslation(388, "en", false, "JAMAICA"),
                new CountryTranslation(400, "en", false, "JORDAN"),
                new CountryTranslation(392, "en", false, "JAPAN"),
                new CountryTranslation(404, "en", false, "KENYA"),
                new CountryTranslation(417, "en", false, "KYRGYZSTAN"),
                new CountryTranslation(116, "en", false, "CAMBODIA"),
                new CountryTranslation(296, "en", false, "KIRIBATI"),
                new CountryTranslation(174, "en", false, "COMOROS"),
                new CountryTranslation(659, "en", false, "SAINT KITTS AND NEVIS"),
                new CountryTranslation(408, "en", false, "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF"),
                new CountryTranslation(410, "en", false, "KOREA, REPUBLIC OF"),
                new CountryTranslation(414, "en", false, "KUWAIT"),
                new CountryTranslation(136, "en", false, "CAYMAN ISLANDS"),
                new CountryTranslation(398, "en", false, "KAZAKHSTAN"),
                new CountryTranslation(418, "en", false, "LAO PEOPLE'S DEMOCRATIC REPUBLIC"),
                new CountryTranslation(422, "en", false, "LEBANON"),
                new CountryTranslation(662, "en", false, "SAINT LUCIA"),
                new CountryTranslation(438, "en", false, "LIECHTENSTEIN"),
                new CountryTranslation(144, "en", false, "SRI LANKA"),
                new CountryTranslation(430, "en", false, "LIBERIA"),
                new CountryTranslation(426, "en", false, "LESOTHO"),
                new CountryTranslation(440, "en", false, "LITHUANIA"),
                new CountryTranslation(442, "en", false, "LUXEMBOURG"),
                new CountryTranslation(428, "en", false, "LATVIA"),
                new CountryTranslation(434, "en", false, "LIBYAN ARAB JAMAHIRIYA"),
                new CountryTranslation(504, "en", false, "MOROCCO"),
                new CountryTranslation(492, "en", false, "MONACO"),
                new CountryTranslation(498, "en", false, "MOLDOVA, REPUBLIC OF"),
                new CountryTranslation(450, "en", false, "MADAGASCAR"),
                new CountryTranslation(584, "en", false, "MARSHALL ISLANDS"),
                new CountryTranslation(807, "en", false, "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF"),
                new CountryTranslation(466, "en", false, "MALI"),
                new CountryTranslation(104, "en", false, "MYANMAR"),
                new CountryTranslation(496, "en", false, "MONGOLIA"),
                new CountryTranslation(446, "en", false, "MACAU"),
                new CountryTranslation(580, "en", false, "NORTHERN MARIANA ISLANDS"),
                new CountryTranslation(474, "en", false, "MARTINIQUE"),
                new CountryTranslation(478, "en", false, "MAURITANIA"),
                new CountryTranslation(500, "en", false, "MONTSERRAT"),
                new CountryTranslation(470, "en", false, "MALTA"),
                new CountryTranslation(480, "en", false, "MAURITIUS"),
                new CountryTranslation(462, "en", false, "MALDIVES"),
                new CountryTranslation(454, "en", false, "MALAWI"),
                new CountryTranslation(484, "en", false, "MEXICO"),
                new CountryTranslation(458, "en", false, "MALAYSIA"),
                new CountryTranslation(508, "en", false, "MOZAMBIQUE"),
                new CountryTranslation(516, "en", false, "NAMIBIA"),
                new CountryTranslation(540, "en", false, "NEW CALEDONIA"),
                new CountryTranslation(562, "en", false, "NIGER"),
                new CountryTranslation(574, "en", false, "NORFOLK ISLAND"),
                new CountryTranslation(566, "en", false, "NIGERIA"),
                new CountryTranslation(558, "en", false, "NICARAGUA"),
                new CountryTranslation(528, "en", false, "NETHERLANDS"),
                new CountryTranslation(578, "en", false, "NORWAY"),
                new CountryTranslation(524, "en", false, "NEPAL"),
                new CountryTranslation(520, "en", false, "NAURU"),
                new CountryTranslation(570, "en", false, "NIUE"),
                new CountryTranslation(554, "en", false, "NEW ZEALAND"),
                new CountryTranslation(512, "en", false, "OMAN"),
                new CountryTranslation(591, "en", false, "PANAMA"),
                new CountryTranslation(604, "en", false, "PERU"),
                new CountryTranslation(258, "en", false, "FRENCH POLYNESIA"),
                new CountryTranslation(598, "en", false, "PAPUA NEW GUINEA"),
                new CountryTranslation(608, "en", false, "PHILIPPINES"),
                new CountryTranslation(586, "en", false, "PAKISTAN"),
                new CountryTranslation(616, "en", false, "POLAND"),
                new CountryTranslation(666, "en", false, "SAINT PIERRE AND MIQUELON"),
                new CountryTranslation(612, "en", false, "PITCAIRN"),
                new CountryTranslation(630, "en", false, "PUERTO RICO"),
                new CountryTranslation(275, "en", false, "PALESTINIAN TERRITORY, Occupied"),
                new CountryTranslation(620, "en", false, "PORTUGAL"),
                new CountryTranslation(585, "en", false, "PALAU"),
                new CountryTranslation(600, "en", false, "PARAGUAY"),
                new CountryTranslation(634, "en", false, "QATAR"),
                new CountryTranslation(638, "en", false, "REUNION"),
                new CountryTranslation(642, "en", false, "ROMANIA"),
                new CountryTranslation(643, "en", false, "RUSSIAN FEDERATION"),
                new CountryTranslation(646, "en", false, "RWANDA"),
                new CountryTranslation(682, "en", false, "SAUDI ARABIA"),
                new CountryTranslation(090, "en", false, "SOLOMON ISLANDS"),
                new CountryTranslation(690, "en", false, "SEYCHELLES"),
                new CountryTranslation(736, "en", false, "SUDAN"),
                new CountryTranslation(752, "en", false, "SWEDEN"),
                new CountryTranslation(702, "en", false, "SINGAPORE"),
                new CountryTranslation(654, "en", false, "SAINT HELENA"),
                new CountryTranslation(705, "en", false, "SLOVENIA"),
                new CountryTranslation(744, "en", false, "SVALBARD AND JAN MAYEN ISLANDS"),
                new CountryTranslation(703, "en", false, "SLOVAKIA"),
                new CountryTranslation(694, "en", false, "SIERRA LEONE"),
                new CountryTranslation(674, "en", false, "SAN MARINO"),
                new CountryTranslation(686, "en", false, "SENEGAL"),
                new CountryTranslation(706, "en", false, "SOMALIA"),
                new CountryTranslation(740, "en", false, "SURINAME"),
                new CountryTranslation(678, "en", false, "SAO TOME AND PRINCIPE"),
                new CountryTranslation(222, "en", false, "EL SALVADOR"),
                new CountryTranslation(760, "en", false, "SYRIAN ARAB REPUBLIC"),
                new CountryTranslation(748, "en", false, "SWAZILAND"),
                new CountryTranslation(796, "en", false, "TURKS AND CAICOS ISLANDS"),
                new CountryTranslation(148, "en", false, "CHAD"),
                new CountryTranslation(260, "en", false, "FRENCH SOUTHERN TERRITORIES"),
                new CountryTranslation(768, "en", false, "TOGO"),
                new CountryTranslation(764, "en", false, "THAILAND"),
                new CountryTranslation(762, "en", false, "TAJIKISTAN"),
                new CountryTranslation(772, "en", false, "TOKELAU"),
                new CountryTranslation(626, "en", false, "TIMOR-LESTE"),
                new CountryTranslation(795, "en", false, "TURKMENISTAN"),
                new CountryTranslation(788, "en", false, "TUNISIA"),
                new CountryTranslation(776, "en", false, "TONGA"),
                new CountryTranslation(792, "en", false, "TURKEY"),
                new CountryTranslation(780, "en", false, "TRINIDAD AND TOBAGO"),
                new CountryTranslation(798, "en", false, "TUVALU"),
                new CountryTranslation(158, "en", false, "TAIWAN"),
                new CountryTranslation(834, "en", false, "TANZANIA, UNITED REPUBLIC OF"),
                new CountryTranslation(804, "en", false, "UKRAINE"),
                new CountryTranslation(800, "en", false, "UGANDA"),
                new CountryTranslation(581, "en", false, "UNITED STATES MINOR OUTLYING ISLANDS"),
                new CountryTranslation(840, "en", false, "UNITED STATES"),
                new CountryTranslation(858, "en", false, "URUGUAY"),
                new CountryTranslation(860, "en", false, "UZBEKISTAN"),
                new CountryTranslation(336, "en", false, "VATICAN CITY STATE (HOLY SEE)"),
                new CountryTranslation(670, "en", false, "SAINT VINCENT AND THE GRENADINES"),
                new CountryTranslation(862, "en", false, "VENEZUELA"),
                new CountryTranslation(092, "en", false, "VIRGIN ISLANDS (BRITISH)"),
                new CountryTranslation(850, "en", false, "VIRGIN ISLANDS (U.S.)"),
                new CountryTranslation(704, "en", false, "VIETNAM"),
                new CountryTranslation(548, "en", false, "VANUATU"),
                new CountryTranslation(876, "en", false, "WALLIS AND FUTUNA ISLANDS"),
                new CountryTranslation(882, "en", false, "SAMOA"),
                new CountryTranslation(887, "en", false, "YEMEN"),
                new CountryTranslation(175, "en", false, "MAYOTTE"),
                new CountryTranslation(710, "en", false, "SOUTH AFRICA"),
                new CountryTranslation(894, "en", false, "ZAMBIA"),
                new CountryTranslation(716, "en", false, "ZIMBABWE")









            };
        }

        public static AreaType[] GetAreaTypes()
        {
            return new[]
            {
                new AreaType(1),
                new AreaType(2),
                new AreaType(3),
                new AreaType(4),
            };
        }

        public static AreaTypeTranslation[] GetAreaTypeTranslations()
        {
            return new[]
            {
                // Spanish
                new AreaTypeTranslation(1, "es", true, "Picking"),
                new AreaTypeTranslation(2, "es", true, "Picking (volumen)"),
                new AreaTypeTranslation(3, "es", true, "Irregular"),
                new AreaTypeTranslation(4, "es", true, "Temporal"),

                // English
                new AreaTypeTranslation(1, "en", false, "Picking"),
                new AreaTypeTranslation(2, "en", false, "Picking (volume)"),
                new AreaTypeTranslation(3, "en", false, "Irregular"),
                new AreaTypeTranslation(4, "en", false, "Temporal"),
            };
        }

        public static Menu[] GetMenus()
        {
            var principalMenus = new Menu[]
           {
                new Menu {Code = MenusSeed.Procceses,Order = 1, MustHaveClient = false, Url = "/processes", ImageClass = "fa-tasks"},
                new Menu {Code = MenusSeed.Operations, Order = 2, MustHaveClient = false, Url = "/operations", ImageClass = "fa-cube "},
                new Menu {Code = MenusSeed.Masters, Order = 3, MustHaveClient = false, Url = "/masters", ImageClass = "fa-database"},
                new Menu {Code = MenusSeed.Administration, Order = 4, MustHaveClient = false, Url = "/administration", ImageClass = "fa-dashboard" },
                new Menu {Code = MenusSeed.Planification, Order = 5, MustHaveClient = false, Url = "/planification", ImageClass = "fa-calendar-o"},
           };

            var principalMenuDictionary = principalMenus.ToDictionary(x => x.Code);

            var menus = new Menu[]
            {
                // Procesos:
                new Menu
                {
                    Code = MenusSeed.Inbounds,
                    Order = 10,
                    MustHaveClient = false,
                    ParentMenu = principalMenuDictionary[MenusSeed.Procceses]
                },
                new Menu
                {
                    Code = MenusSeed.StockManagement,
                    Order = 20,
                    MustHaveClient = false,
                    ParentMenu = principalMenuDictionary[MenusSeed.Procceses]
                },
                new Menu
                {
                    Code = MenusSeed.Picking,
                    Order = 30,
                    MustHaveClient = false,
                    ParentMenu = principalMenuDictionary[MenusSeed.Procceses]
                },
                new Menu
                {
                    Code = MenusSeed.Expeditions,
                    Order = 40,
                    MustHaveClient = false,
                    ParentMenu = principalMenuDictionary[MenusSeed.Procceses]
                },
                //Administración:
                new Menu
                {
                    Code = MenusSeed.WarehousesManagement,
                    Order = 10,
                    MustHaveClient = false,
                    ParentMenu = principalMenuDictionary[MenusSeed.Administration],
                    ImageClass = "fa-cubes"
                },
                new Menu
                {
                    Code = MenusSeed.ClientsManagement,
                    Order = 20,
                    MustHaveClient = false,
                    ParentMenu = principalMenuDictionary[MenusSeed.Administration],
                    ImageClass = "fa-user-md"
                },
                new Menu
                {
                    Code = MenusSeed.CompaniesManagement,
                    Order = 30,
                    MustHaveClient = false,
                    ParentMenu = principalMenuDictionary[MenusSeed.Administration],
                    ImageClass = "fa-suitcase"
                },
                new Menu
                {
                    Code = MenusSeed.WorkstationsManagement,
                    Order = 40,
                    MustHaveClient = false,
                    ParentMenu = principalMenuDictionary[MenusSeed.Administration],
                    ImageClass = "fa-desktop "
                },
                new Menu
                {
                    Code = MenusSeed.UsersManagement,
                    Order = 50,
                    MustHaveClient = false,
                    ParentMenu = principalMenuDictionary[MenusSeed.Administration],
                    ImageClass = "fa-users"
                },
                // Maestros del cliente:
                new Menu
                {
                    Code = ClientActions.Addressees,
                    Order = 10,
                    MustHaveClient = true,
                    Url = "/masters/addressees",
                    ParentMenu = principalMenuDictionary[MenusSeed.Masters],
                    ImageClass = "fa-mail-forward"
                },
                new Menu
                {
                    Code = ClientActions.Items,
                    Order = 20,
                    MustHaveClient = true,
                    Url = "/masters/items",
                    ParentMenu = principalMenuDictionary[MenusSeed.Masters],
                    ImageClass = "fa-cube"
                },
                new Menu
                {
                    Code = ClientActions.Families,
                    Order = 30,
                    MustHaveClient = true,
                    Url = "/masters/families",
                    ParentMenu = principalMenuDictionary[MenusSeed.Masters],
                    ImageClass = "fa-object-group"
                }
            };

            var menuDictionary = menus.ToDictionary(x => x.Code);

            var submenus = new Menu[]
            {
                 //Gestión de almacenes:
                new Menu
                {
                    Code = MenusSeed.Areas,
                    Order = 10,
                    MustHaveClient = false,
                    Url = "/administration/warehouse-management/areas",
                    ParentMenu = menuDictionary[MenusSeed.WarehousesManagement]
                },
                new Menu
                {
                    Code = MenusSeed.BinLocations,
                    Order = 20,
                    MustHaveClient = false,
                    Url = "/administration/warehouse-management/bin-locations",
                    ParentMenu = menuDictionary[MenusSeed.WarehousesManagement]
                },new Menu
                {
                    Code = MenusSeed.PackingTypes,
                    Order = 30,
                    MustHaveClient = false,
                    Url = "/administration/warehouse-management/packing-types",
                    ParentMenu = menuDictionary[MenusSeed.WarehousesManagement]
                },
                new Menu
                {
                    Code = MenusSeed.SorterTypes,
                    Order = 40,
                    MustHaveClient = false,
                    Url = "/administration/warehouse-management/sorter-types",
                    ParentMenu = menuDictionary[MenusSeed.WarehousesManagement]
                },
                // Gestión de empresas
                new Menu
                {
                    Code = MenusSeed.Companies,
                    Order = 10,
                    MustHaveClient = false,
                    Url = "/administration/companies-management/companies",
                    ParentMenu = menuDictionary[MenusSeed.CompaniesManagement]
                },
                // Gestión de clientes
                new Menu
                {
                    Code = MenusSeed.Clients,
                    Order = 10,
                    MustHaveClient = false,
                    Url = "/administration/clients-management/clients",
                    ParentMenu = menuDictionary[MenusSeed.ClientsManagement]
                },
                // Gestión de puestos
                new Menu
                {
                    Code = MenusSeed.Workstations,
                    Order = 10,
                    MustHaveClient = false,
                    Url = "/administration/workstations-management/workstations",
                    ParentMenu = menuDictionary[MenusSeed.WorkstationsManagement]
                },
                // Gestión de usuarios
                new Menu
                {
                    Code = MenusSeed.Users,
                    Order = 10,
                    MustHaveClient = false,
                    Url = "/administration/users-management/users",
                    ParentMenu = menuDictionary[MenusSeed.UsersManagement]
                },
                // Entradas
                new Menu
                {
                    Code = MenusSeed.InboundsManagement,
                    Order = 10,
                    MustHaveClient = true,
                    Url = "/processes/inbounds/inbounds-management",
                    ParentMenu = menuDictionary[MenusSeed.Inbounds]
                },
            };

            var allmenus = new List<Menu>();
            allmenus.AddRange(principalMenus);
            allmenus.AddRange(menus);
            allmenus.AddRange(submenus);
            return allmenus.ToArray();
        }

        public static MenuTranslation[] GetMenuTranslations()
        {
            return new MenuTranslation[]
            {
                // Spanish
                new MenuTranslation(MenusSeed.Procceses, "es", true, "Procesos"),
                new MenuTranslation(MenusSeed.Operations, "es", true, "Operaciones"),
                new MenuTranslation(MenusSeed.Masters, "es", true, "Maestros"),
                new MenuTranslation(MenusSeed.Administration, "es", true, "Administración"),
                new MenuTranslation(MenusSeed.Planification, "es", true, "Planificación"),
                ////----
                new MenuTranslation(MenusSeed.WarehousesManagement, "es", true, "Gestión de almacenes"),
                new MenuTranslation(MenusSeed.ClientsManagement, "es", true, "Gestión de clientes"),
                new MenuTranslation(MenusSeed.CompaniesManagement, "es", true, "Gestión de empresas"),
                new MenuTranslation(MenusSeed.WorkstationsManagement, "es", true, "Gestión de puestos"),
                new MenuTranslation(MenusSeed.UsersManagement, "es", true, "Gestión de usuarios"),
                new MenuTranslation(MenusSeed.Inbounds, "es", true, "Entradas"),
                new MenuTranslation(MenusSeed.StockManagement, "es", true, "Gestión de stock"),
                new MenuTranslation(MenusSeed.Picking, "es", true, "Picking"),
                new MenuTranslation(MenusSeed.Expeditions, "es", true, "Expediciones"),
                ////----
                new MenuTranslation(MenusSeed.Areas, "es", true, "Áreas"),
                new MenuTranslation(MenusSeed.BinLocations, "es", true, "Huecos"),
                new MenuTranslation(MenusSeed.PackingTypes, "es", true, "Tipos de packing"),
                new MenuTranslation(MenusSeed.SorterTypes, "es", true, "Tipos de sorter"),
                new MenuTranslation(MenusSeed.Companies, "es", true, "Empresas"),
                new MenuTranslation(MenusSeed.Clients, "es", true, "Clientes"),
                new MenuTranslation(ClientActions.Addressees, "es", true, "Destinatarios"),
                new MenuTranslation(ClientActions.Items, "es", true, "Items"),
                new MenuTranslation(ClientActions.Families, "es", true, "Familias"),
                new MenuTranslation(MenusSeed.Workstations, "es", true, "Puestos"),
                new MenuTranslation(MenusSeed.Users, "es", true, "Usuarios"),
                new MenuTranslation(MenusSeed.InboundsManagement, "es", true, "Gestión de entradas"),

                //// English
                new MenuTranslation(MenusSeed.Procceses, "en", false, "Procceses"),
                new MenuTranslation(MenusSeed.Operations, "en", false, "Operations"),
                new MenuTranslation(MenusSeed.Masters, "en", false, "Masters"),
                new MenuTranslation(MenusSeed.Administration, "en", false, "Administration"),
                new MenuTranslation(MenusSeed.Planification, "en", false, "Planification"),
                ////----
                new MenuTranslation(MenusSeed.WarehousesManagement, "en", false, "Warehouses management"),
                new MenuTranslation(MenusSeed.ClientsManagement, "en", false, "Clients management"),
                new MenuTranslation(MenusSeed.CompaniesManagement, "en", false, "Companies management"),
                new MenuTranslation(MenusSeed.WorkstationsManagement, "en", false, "Workstations management"),
                new MenuTranslation(MenusSeed.UsersManagement, "en", false, "Users management"),
                new MenuTranslation(MenusSeed.Inbounds, "en", false, "Inbounds"),
                new MenuTranslation(MenusSeed.StockManagement, "en", false, "StockManagement"),
                new MenuTranslation(MenusSeed.Picking, "en", false, "Picking"),
                new MenuTranslation(MenusSeed.Expeditions, "en", false, "Expeditions"),
                ////----
                new MenuTranslation(MenusSeed.Areas, "en", false, "Areas"),
                new MenuTranslation(MenusSeed.BinLocations, "en", false, "Bin locations"),
                new MenuTranslation(MenusSeed.PackingTypes, "en", false, "Packing types"),
                new MenuTranslation(MenusSeed.SorterTypes, "en", false, "Sorter types"),
                new MenuTranslation(MenusSeed.Companies, "en", false, "Companies"),
                new MenuTranslation(MenusSeed.Clients, "en", false, "Clients"),
                new MenuTranslation(ClientActions.Addressees, "en", false, "Addressees"),
                new MenuTranslation(ClientActions.Items, "en", false, "Items"),
                new MenuTranslation(ClientActions.Families, "en", false, "Families"),
                new MenuTranslation(MenusSeed.Workstations, "en", false, "Workstations"),
                new MenuTranslation(MenusSeed.Users, "en", false, "Users"),
                new MenuTranslation(MenusSeed.InboundsManagement, "en", false, "InboundsManagement"),
            };
        }

        public static ItemType[] GetItemypes()
        {
            return new[]
            {
                new ItemType(1),
                new ItemType(2),
                new ItemType(3),
            };
        }

        public static ItemTypeTranslation[] GetItemTypeTranslations()
        {
            return new[]
            {
                // Spanish
                new ItemTypeTranslation(1, "es", true, "Artículo"),
                new ItemTypeTranslation(2, "es", true, "Pack"),
                new ItemTypeTranslation(3, "es", true, "Multipack"),

                // English
                new ItemTypeTranslation(1, "en", false, "Article"),
                new ItemTypeTranslation(2, "en", false, "Pack"),
                new ItemTypeTranslation(3, "en", false, "Multipack"),
            };
        }
    }
}
