﻿﻿using System.Collections.Generic;
using System.Linq;
using Logisfashion.LogisCore.Common.Seeds.Shared.Constants;
using Logisfashion.LogisCore.SharedBC.Model;
using Logisfashion.LogisCore.Seedwork;

namespace Logisfashion.LogisCore.Common.Seeds.Shared.Data
{
    public static class CommonSeed
    {
        public static Country[] GetCountries()
        {
            return new[]
            {
                new Country(4, "AF", "AFG"),
                new Country(248, "AX", "ALA"),
                new Country(8, "AL", "ALB"),
                new Country(276, "DE", "DEU"),
                new Country(20, "AD", "AND"),
                new Country(24, "AO", "AGO"),
                new Country(660, "AI", "AIA"),
                new Country(10, "AQ", "ATA"),
                new Country(28, "AG", "ATG"),
                new Country(682, "SA", "SAU"),
                new Country(12, "DZ", "DZA"),
                new Country(32, "AR", "ARG"),
                new Country(51, "AM", "ARM"),
                new Country(533, "AW", "ABW"),
                new Country(36, "AU", "AUS"),
                new Country(40, "AT", "AUT"),
                new Country(31, "AZ", "AZE"),
                new Country(44, "BS", "BHS"),
                new Country(50, "BD", "BGD"),
                new Country(52, "BB", "BRB"),
                new Country(48, "BH", "BHR"),
                new Country(56, "BE", "BEL"),
                new Country(84, "BZ", "BLZ"),
                new Country(204, "BJ", "BEN"),
                new Country(60, "BM", "BMU"),
                new Country(112, "BY", "BLR"),
                new Country(68, "BO", "BOL"),
                new Country(535, "BQ", "BES"),
                new Country(70, "BA", "BIH"),
                new Country(72, "BW", "BWA"),
                new Country(76, "BR", "BRA"),
                new Country(96, "BN", "BRN"),
                new Country(100, "BG", "BGR"),
                new Country(854, "BF", "BFA"),
                new Country(108, "BI", "BDI"),
                new Country(64, "BT", "BTN"),
                new Country(132, "CV", "CPV"),
                new Country(116, "KH", "KHM"),
                new Country(120, "CM", "CMR"),
                new Country(124, "CA", "CAN"),
                new Country(634, "QA", "QAT"),
                new Country(148, "TD", "TCD"),
                new Country(152, "CL", "CHL"),
                new Country(156, "CN", "CHN"),
                new Country(196, "CY", "CYP"),
                new Country(170, "CO", "COL"),
                new Country(174, "KM", "COM"),
                new Country(408, "KP", "PRK"),
                new Country(410, "KR", "KOR"),
                new Country(384, "CI", "CIV"),
                new Country(188, "CR", "CRI"),
                new Country(191, "HR", "HRV"),
                new Country(192, "CU", "CUB"),
                new Country(531, "CW", "CUW"),
                new Country(208, "DK", "DNK"),
                new Country(212, "DM", "DMA"),
                new Country(218, "EC", "ECU"),
                new Country(818, "EG", "EGY"),
                new Country(222, "SV", "SLV"),
                new Country(784, "AE", "ARE"),
                new Country(232, "ER", "ERI"),
                new Country(703, "SK", "SVK"),
                new Country(705, "SI", "SVN"),
                new Country(724, "ES", "ESP"),
                new Country(840, "US", "USA"),
                new Country(233, "EE", "EST"),
                new Country(231, "ET", "ETH"),
                new Country(608, "PH", "PHL"),
                new Country(246, "FI", "FIN"),
                new Country(242, "FJ", "FJI"),
                new Country(250, "FR", "FRA"),
                new Country(266, "GA", "GAB"),
                new Country(270, "GM", "GMB"),
                new Country(268, "GE", "GEO"),
                new Country(288, "GH", "GHA"),
                new Country(292, "GI", "GIB"),
                new Country(308, "GD", "GRD"),
                new Country(300, "GR", "GRC"),
                new Country(304, "GL", "GRL"),
                new Country(312, "GP", "GLP"),
                new Country(316, "GU", "GUM"),
                new Country(320, "GT", "GTM"),
                new Country(254, "GF", "GUF"),
                new Country(831, "GG", "GGY"),
                new Country(324, "GN", "GIN"),
                new Country(624, "GW", "GNB"),
                new Country(226, "GQ", "GNQ"),
                new Country(328, "GY", "GUY"),
                new Country(332, "HT", "HTI"),
                new Country(340, "HN", "HND"),
                new Country(344, "HK", "HKG"),
                new Country(348, "HU", "HUN"),
                new Country(356, "IN", "IND"),
                new Country(360, "ID", "IDN"),
                new Country(368, "IQ", "IRQ"),
                new Country(364, "IR", "IRN"),
                new Country(372, "IE", "IRL"),
                new Country(74, "BV", "BVT"),
                new Country(833, "IM", "IMN"),
                new Country(162, "CX", "CXR"),
                new Country(352, "IS", "ISL"),
                new Country(136, "KY", "CYM"),
                new Country(166, "CC", "CCK"),
                new Country(184, "CK", "COK"),
                new Country(234, "FO", "FRO"),
                new Country(239, "GS", "SGS"),
                new Country(334, "HM", "HMD"),
                new Country(238, "FK", "FLK"),
                new Country(580, "MP", "MNP"),
                new Country(584, "MH", "MHL"),
                new Country(612, "PN", "PCN"),
                new Country(90, "SB", "SLB"),
                new Country(796, "TC", "TCA"),
                new Country(581, "UM", "UMI"),
                new Country(92, "VG", "VGB"),
                new Country(850, "VI", "VIR"),
                new Country(376, "IL", "ISR"),
                new Country(380, "IT", "ITA"),
                new Country(388, "JM", "JAM"),
                new Country(392, "JP", "JPN"),
                new Country(832, "JE", "JEY"),
                new Country(400, "JO", "JOR"),
                new Country(398, "KZ", "KAZ"),
                new Country(404, "KE", "KEN"),
                new Country(417, "KG", "KGZ"),
                new Country(296, "KI", "KIR"),
                new Country(414, "KW", "KWT"),
                new Country(418, "LA", "LAO"),
                new Country(426, "LS", "LSO"),
                new Country(428, "LV", "LVA"),
                new Country(422, "LB", "LBN"),
                new Country(430, "LR", "LBR"),
                new Country(434, "LY", "LBY"),
                new Country(438, "LI", "LIE"),
                new Country(440, "LT", "LTU"),
                new Country(442, "LU", "LUX"),
                new Country(446, "MO", "MAC"),
                new Country(807, "MK", "MKD"),
                new Country(450, "MG", "MDG"),
                new Country(458, "MY", "MYS"),
                new Country(454, "MW", "MWI"),
                new Country(462, "MV", "MDV"),
                new Country(466, "ML", "MLI"),
                new Country(470, "MT", "MLT"),
                new Country(504, "MA", "MAR"),
                new Country(474, "MQ", "MTQ"),
                new Country(480, "MU", "MUS"),
                new Country(478, "MR", "MRT"),
                new Country(175, "YT", "MYT"),
                new Country(484, "MX", "MEX"),
                new Country(583, "FM", "FSM"),
                new Country(498, "MD", "MDA"),
                new Country(492, "MC", "MCO"),
                new Country(496, "MN", "MNG"),
                new Country(499, "ME", "MNE"),
                new Country(500, "MS", "MSR"),
                new Country(508, "MZ", "MOZ"),
                new Country(104, "MM", "MMR"),
                new Country(516, "NA", "NAM"),
                new Country(520, "NR", "NRU"),
                new Country(524, "NP", "NPL"),
                new Country(558, "NI", "NIC"),
                new Country(562, "NE", "NER"),
                new Country(566, "NG", "NGA"),
                new Country(570, "NU", "NIU"),
                new Country(574, "NF", "NFK"),
                new Country(578, "NO", "NOR"),
                new Country(540, "NC", "NCL"),
                new Country(554, "NZ", "NZL"),
                new Country(512, "OM", "OMN"),
                new Country(528, "NL", "NLD"),
                new Country(586, "PK", "PAK"),
                new Country(585, "PW", "PLW"),
                new Country(275, "PS", "PSE"),
                new Country(591, "PA", "PAN"),
                new Country(598, "PG", "PNG"),
                new Country(600, "PY", "PRY"),
                new Country(604, "PE", "PER"),
                new Country(258, "PF", "PYF"),
                new Country(616, "PL", "POL"),
                new Country(620, "PT", "PRT"),
                new Country(630, "PR", "PRI"),
                new Country(826, "GB", "GBR"),
                new Country(732, "EH", "ESH"),
                new Country(140, "CF", "CAF"),
                new Country(203, "CZ", "CZE"),
                new Country(178, "CG", "COG"),
                new Country(180, "CD", "COD"),
                new Country(214, "DO", "DOM"),
                new Country(638, "RE", "REU"),
                new Country(646, "RW", "RWA"),
                new Country(642, "RO", "ROU"),
                new Country(643, "RU", "RUS"),
                new Country(882, "WS", "WSM"),
                new Country(16, "AS", "ASM"),
                new Country(652, "BL", "BLM"),
                new Country(659, "KN", "KNA"),
                new Country(674, "SM", "SMR"),
                new Country(663, "MF", "MAF"),
                new Country(666, "PM", "SPM"),
                new Country(670, "VC", "VCT"),
                new Country(654, "SH", "SHN"),
                new Country(662, "LC", "LCA"),
                new Country(678, "ST", "STP"),
                new Country(686, "SN", "SEN"),
                new Country(688, "RS", "SRB"),
                new Country(690, "SC", "SYC"),
                new Country(694, "SL", "SLE"),
                new Country(702, "SG", "SGP"),
                new Country(534, "SX", "SXM"),
                new Country(760, "SY", "SYR"),
                new Country(706, "SO", "SOM"),
                new Country(144, "LK", "LKA"),
                new Country(748, "SZ", "SWZ"),
                new Country(710, "ZA", "ZAF"),
                new Country(729, "SD", "SDN"),
                new Country(728, "SS", "SSD"),
                new Country(752, "SE", "SWE"),
                new Country(756, "CH", "CHE"),
                new Country(740, "SR", "SUR"),
                new Country(744, "SJ", "SJM"),
                new Country(764, "TH", "THA"),
                new Country(158, "TW", "TWN"),
                new Country(834, "TZ", "TZA"),
                new Country(762, "TJ", "TJK"),
                new Country(86 , "IO", "IOT"),
                new Country(260, "TF", "ATF"),
                new Country(626, "TL", "TLS"),
                new Country(768, "TG", "TGO"),
                new Country(772, "TK", "TKL"),
                new Country(776, "TO", "TON"),
                new Country(780, "TT", "TTO"),
                new Country(788, "TN", "TUN"),
                new Country(795, "TM", "TKM"),
                new Country(792, "TR", "TUR"),
                new Country(798, "TV", "TUV"),
                new Country(804, "UA", "UKR"),
                new Country(800, "UG", "UGA"),
                new Country(858, "UY", "URY"),
                new Country(860, "UZ", "UZB"),
                new Country(548, "VU", "VUT"),
                new Country(336, "VA", "VAT"),
                new Country(862, "VE", "VEN"),
                new Country(704, "VN", "VNM"),
                new Country(876, "WF", "WLF"),
                new Country(887, "YE", "YEM"),
                new Country(262, "DJ", "DJI"),
                new Country(894, "ZM", "ZMB"),
                new Country(716, "ZW", "ZWE")                
            };
        }

        public static CountryTranslation[] GetCountryTranslations()
        {
            return new[]
            {
                // Spanish
                new CountryTranslation(4  , "es", true, "Afganistán"),
                new CountryTranslation(248, "es", true, "Åland"),
                new CountryTranslation(8  , "es", true, "Albania"),
                new CountryTranslation(276, "es", true, "Alemania"),
                new CountryTranslation(20 , "es", true, "Andorra"),
                new CountryTranslation(24 , "es", true, "Angola"),
                new CountryTranslation(660, "es", true, "Anguila"),
                new CountryTranslation(10 , "es", true, "Antártida"),
                new CountryTranslation(28 , "es", true, "Antigua y Barbuda"),
                new CountryTranslation(682, "es", true, "Arabia Saudita"),
                new CountryTranslation(12 , "es", true, "Argelia"),
                new CountryTranslation(32 , "es", true, "Argentina"),
                new CountryTranslation(51 , "es", true, "Armenia"),
                new CountryTranslation(533, "es", true, "Aruba"),
                new CountryTranslation(36 , "es", true, "Australia"),
                new CountryTranslation(40 , "es", true, "Austria"),
                new CountryTranslation(31 , "es", true, "Azerbaiyán"),
                new CountryTranslation(44 , "es", true, "Bahamas"),
                new CountryTranslation(50 , "es", true, "Bangladés"),
                new CountryTranslation(52 , "es", true, "Barbados"),
                new CountryTranslation(48 , "es", true, "Baréin"),
                new CountryTranslation(56 , "es", true, "Bélgica"),
                new CountryTranslation(84 , "es", true, "Belice"),
                new CountryTranslation(204, "es", true, "Benín"),
                new CountryTranslation(60 , "es", true, "Bermudas"),
                new CountryTranslation(112, "es", true, "Bielorrusia"),
                new CountryTranslation(68 , "es", true, "Bolivia"),
                new CountryTranslation(535, "es", true, "Bonaire, San Eustaquio y Saba"),
                new CountryTranslation(70 , "es", true, "Bosnia y Herzegovina"),
                new CountryTranslation(72 , "es", true, "Botsuana"),
                new CountryTranslation(76 , "es", true, "Brasil"),
                new CountryTranslation(96 , "es", true, "Brunéi"),
                new CountryTranslation(100, "es", true, "Bulgaria"),
                new CountryTranslation(854, "es", true, "Burkina Faso"),
                new CountryTranslation(108, "es", true, "Burundi"),
                new CountryTranslation(64 , "es", true, "Bután"),
                new CountryTranslation(132, "es", true, "Cabo Verde"),
                new CountryTranslation(116, "es", true, "Camboya"),
                new CountryTranslation(120, "es", true, "Camerún"),
                new CountryTranslation(124, "es", true, "Canadá"),
                new CountryTranslation(634, "es", true, "Catar"),
                new CountryTranslation(148, "es", true, "Chad"),
                new CountryTranslation(152, "es", true, "Chile"),
                new CountryTranslation(156, "es", true, "China"),
                new CountryTranslation(196, "es", true, "Chipre"),
                new CountryTranslation(170, "es", true, "Colombia"),
                new CountryTranslation(174, "es", true, "Comoras"),
                new CountryTranslation(408, "es", true, "Corea del Norte"),
                new CountryTranslation(410, "es", true, "Corea del Sur"),
                new CountryTranslation(384, "es", true, "Costa de Marfil"),
                new CountryTranslation(188, "es", true, "Costa Rica"),
                new CountryTranslation(191, "es", true, "Croacia"),
                new CountryTranslation(192, "es", true, "Cuba"),
                new CountryTranslation(531, "es", true, "Curazao"),
                new CountryTranslation(208, "es", true, "Dinamarca"),
                new CountryTranslation(212, "es", true, "Dominica"),
                new CountryTranslation(218, "es", true, "Ecuador"),
                new CountryTranslation(818, "es", true, "Egipto"),
                new CountryTranslation(222, "es", true, "El Salvador"),
                new CountryTranslation(784, "es", true, "Emiratos Árabes Unidos"),
                new CountryTranslation(232, "es", true, "Eritrea"),
                new CountryTranslation(703, "es", true, "Eslovaquia"),
                new CountryTranslation(705, "es", true, "Eslovenia"),
                new CountryTranslation(724, "es", true, "España"),
                new CountryTranslation(840, "es", true, "Estados Unidos"),
                new CountryTranslation(233, "es", true, "Estonia"),
                new CountryTranslation(231, "es", true, "Etiopía"),
                new CountryTranslation(608, "es", true, "Filipinas"),
                new CountryTranslation(246, "es", true, "Finlandia"),
                new CountryTranslation(242, "es", true, "Fiyi"),
                new CountryTranslation(250, "es", true, "Francia"),
                new CountryTranslation(266, "es", true, "Gabón"),
                new CountryTranslation(270, "es", true, "Gambia"),
                new CountryTranslation(268, "es", true, "Georgia"),
                new CountryTranslation(288, "es", true, "Ghana"),
                new CountryTranslation(292, "es", true, "Gibraltar"),
                new CountryTranslation(308, "es", true, "Granada"),
                new CountryTranslation(300, "es", true, "Grecia"),
                new CountryTranslation(304, "es", true, "Groenlandia"),
                new CountryTranslation(312, "es", true, "Guadalupe"),
                new CountryTranslation(316, "es", true, "Guam"),
                new CountryTranslation(320, "es", true, "Guatemala"),
                new CountryTranslation(254, "es", true, "Guayana Francesa"),
                new CountryTranslation(831, "es", true, "Guernsey"),
                new CountryTranslation(324, "es", true, "Guinea"),
                new CountryTranslation(624, "es", true, "Guinea-Bisáu"),
                new CountryTranslation(226, "es", true, "Guinea Ecuatorial"),
                new CountryTranslation(328, "es", true, "Guyana"),
                new CountryTranslation(332, "es", true, "Haití"),
                new CountryTranslation(340, "es", true, "Honduras"),
                new CountryTranslation(344, "es", true, "Hong Kong"),
                new CountryTranslation(348, "es", true, "Hungría"),
                new CountryTranslation(356, "es", true, "India"),
                new CountryTranslation(360, "es", true, "Indonesia"),
                new CountryTranslation(368, "es", true, "Irak"),
                new CountryTranslation(364, "es", true, "Irán"),
                new CountryTranslation(372, "es", true, "Irlanda"),
                new CountryTranslation(74 , "es", true, "Isla Bouvet"),
                new CountryTranslation(833, "es", true, "Isla de Man"),
                new CountryTranslation(162, "es", true, "Isla de Navidad"),
                new CountryTranslation(352, "es", true, "Islandia"),
                new CountryTranslation(136, "es", true, "Islas Caimán"),
                new CountryTranslation(166, "es", true, "Islas Cocos"),
                new CountryTranslation(184, "es", true, "Islas Cook"),
                new CountryTranslation(234, "es", true, "Islas Feroe"),
                new CountryTranslation(239, "es", true, "Islas Georgias del Sur y Sandwich del Sur"),
                new CountryTranslation(334, "es", true, "Islas Heard y McDonald"),
                new CountryTranslation(238, "es", true, "Islas Malvinas"),
                new CountryTranslation(580, "es", true, "Islas Marianas del Norte"),
                new CountryTranslation(584, "es", true, "Islas Marshall"),
                new CountryTranslation(612, "es", true, "Islas Pitcairn"),
                new CountryTranslation(90 , "es", true, "Islas Salomón"),
                new CountryTranslation(796, "es", true, "Islas Turcas y Caicos"),
                new CountryTranslation(581, "es", true, "Islas ultramarinas de Estados Unidos"),
                new CountryTranslation(92 , "es", true, "Islas Vírgenes Británicas"),
                new CountryTranslation(850, "es", true, "Islas Vírgenes de los Estados Unidos"),
                new CountryTranslation(376, "es", true, "Israel"),
                new CountryTranslation(380, "es", true, "Italia"),
                new CountryTranslation(388, "es", true, "Jamaica"),
                new CountryTranslation(392, "es", true, "Japón"),
                new CountryTranslation(832, "es", true, "Jersey"),
                new CountryTranslation(400, "es", true, "Jordania"),
                new CountryTranslation(398, "es", true, "Kazajistán"),
                new CountryTranslation(404, "es", true, "Kenia"),
                new CountryTranslation(417, "es", true, "Kirguistán"),
                new CountryTranslation(296, "es", true, "Kiribati"),
                new CountryTranslation(414, "es", true, "Kuwait"),
                new CountryTranslation(418, "es", true, "Laos"),
                new CountryTranslation(426, "es", true, "Lesoto"),
                new CountryTranslation(428, "es", true, "Letonia"),
                new CountryTranslation(422, "es", true, "Líbano"),
                new CountryTranslation(430, "es", true, "Liberia"),
                new CountryTranslation(434, "es", true, "Libia"),
                new CountryTranslation(438, "es", true, "Liechtenstein"),
                new CountryTranslation(440, "es", true, "Lituania"),
                new CountryTranslation(442, "es", true, "Luxemburgo"),
                new CountryTranslation(446, "es", true, "Macao"),
                new CountryTranslation(807, "es", true, "Macedonia"),
                new CountryTranslation(450, "es", true, "Madagascar"),
                new CountryTranslation(458, "es", true, "Malasia"),
                new CountryTranslation(454, "es", true, "Malaui"),
                new CountryTranslation(462, "es", true, "Maldivas"),
                new CountryTranslation(466, "es", true, "Malí"),
                new CountryTranslation(470, "es", true, "Malta"),
                new CountryTranslation(504, "es", true, "Marruecos"),
                new CountryTranslation(474, "es", true, "Martinica"),
                new CountryTranslation(480, "es", true, "Mauricio"),
                new CountryTranslation(478, "es", true, "Mauritania"),
                new CountryTranslation(175, "es", true, "Mayotte"),
                new CountryTranslation(484, "es", true, "México"),
                new CountryTranslation(583, "es", true, "Micronesia"),
                new CountryTranslation(498, "es", true, "Moldavia"),
                new CountryTranslation(492, "es", true, "Mónaco"),
                new CountryTranslation(496, "es", true, "Mongolia"),
                new CountryTranslation(499, "es", true, "Montenegro"),
                new CountryTranslation(500, "es", true, "Montserrat"),
                new CountryTranslation(508, "es", true, "Mozambique"),
                new CountryTranslation(104, "es", true, "Myanmar"),
                new CountryTranslation(516, "es", true, "Namibia"),
                new CountryTranslation(520, "es", true, "Nauru"),
                new CountryTranslation(524, "es", true, "Nepal"),
                new CountryTranslation(558, "es", true, "Nicaragua"),
                new CountryTranslation(562, "es", true, "Níger"),
                new CountryTranslation(566, "es", true, "Nigeria"),
                new CountryTranslation(570, "es", true, "Niue"),
                new CountryTranslation(574, "es", true, "Norfolk"),
                new CountryTranslation(578, "es", true, "Noruega"),
                new CountryTranslation(540, "es", true, "Nueva Caledonia"),
                new CountryTranslation(554, "es", true, "Nueva Zelanda"),
                new CountryTranslation(512, "es", true, "Omán"),
                new CountryTranslation(528, "es", true, "Países Bajos"),
                new CountryTranslation(586, "es", true, "Pakistán"),
                new CountryTranslation(585, "es", true, "Palaos"),
                new CountryTranslation(275, "es", true, "Palestina"),
                new CountryTranslation(591, "es", true, "Panamá"),
                new CountryTranslation(598, "es", true, "Papúa Nueva Guinea"),
                new CountryTranslation(600, "es", true, "Paraguay"),
                new CountryTranslation(604, "es", true, "Perú"),
                new CountryTranslation(258, "es", true, "Polinesia Francesa"),
                new CountryTranslation(616, "es", true, "Polonia"),
                new CountryTranslation(620, "es", true, "Portugal"),
                new CountryTranslation(630, "es", true, "Puerto Rico"),
                new CountryTranslation(826, "es", true, "Reino Unido"),
                new CountryTranslation(732, "es", true, "República Árabe Saharaui Democrática"),
                new CountryTranslation(140, "es", true, "República Centroafricana"),
                new CountryTranslation(203, "es", true, "República Checa"),
                new CountryTranslation(178, "es", true, "República del Congo"),
                new CountryTranslation(180, "es", true, "República Democrática del Congo"),
                new CountryTranslation(214, "es", true, "República Dominicana"),
                new CountryTranslation(638, "es", true, "Reunión"),
                new CountryTranslation(646, "es", true, "Ruanda"),
                new CountryTranslation(642, "es", true, "Rumania"),
                new CountryTranslation(643, "es", true, "Rusia"),
                new CountryTranslation(882, "es", true, "Samoa"),
                new CountryTranslation(16 , "es", true, "Samoa Americana"),
                new CountryTranslation(652, "es", true, "San Bartolomé"),
                new CountryTranslation(659, "es", true, "San Cristóbal y Nieves"),
                new CountryTranslation(674, "es", true, "San Marino"),
                new CountryTranslation(663, "es", true, "San Martín"),
                new CountryTranslation(666, "es", true, "San Pedro y Miquelón"),
                new CountryTranslation(670, "es", true, "San Vicente y las Granadinas"),
                new CountryTranslation(654, "es", true, "Santa Elena, Ascensión y Tristán de Acuña"),
                new CountryTranslation(662, "es", true, "Santa Lucía"),
                new CountryTranslation(678, "es", true, "Santo Tomé y Príncipe"),
                new CountryTranslation(686, "es", true, "Senegal"),
                new CountryTranslation(688, "es", true, "Serbia"),
                new CountryTranslation(690, "es", true, "Seychelles"),
                new CountryTranslation(694, "es", true, "Sierra Leona"),
                new CountryTranslation(702, "es", true, "Singapur"),
                new CountryTranslation(534, "es", true, "Sint Maarten"),
                new CountryTranslation(760, "es", true, "Siria"),
                new CountryTranslation(706, "es", true, "Somalia"),
                new CountryTranslation(144, "es", true, "Sri Lanka"),
                new CountryTranslation(748, "es", true, "Suazilandia"),
                new CountryTranslation(710, "es", true, "Sudáfrica"),
                new CountryTranslation(729, "es", true, "Sudán"),
                new CountryTranslation(728, "es", true, "Sudán del Sur"),
                new CountryTranslation(752, "es", true, "Suecia"),
                new CountryTranslation(756, "es", true, "Suiza"),
                new CountryTranslation(740, "es", true, "Surinam"),
                new CountryTranslation(744, "es", true, "Svalbard y Jan Mayen"),
                new CountryTranslation(764, "es", true, "Tailandia"),
                new CountryTranslation(158, "es", true, "Taiwán (República de China)"),
                new CountryTranslation(834, "es", true, "Tanzania"),
                new CountryTranslation(762, "es", true, "Tayikistán"),
                new CountryTranslation(86 , "es", true, "Territorio Británico del Océano Índico"),
                new CountryTranslation(260, "es", true, "Tierras Australes y Antárticas Francesas"),
                new CountryTranslation(626, "es", true, "Timor Oriental"),
                new CountryTranslation(768, "es", true, "Togo"),
                new CountryTranslation(772, "es", true, "Tokelau"),
                new CountryTranslation(776, "es", true, "Tonga"),
                new CountryTranslation(780, "es", true, "Trinidad y Tobago"),
                new CountryTranslation(788, "es", true, "Túnez"),
                new CountryTranslation(795, "es", true, "Turkmenistán"),
                new CountryTranslation(792, "es", true, "Turquía"),
                new CountryTranslation(798, "es", true, "Tuvalu"),
                new CountryTranslation(804, "es", true, "Ucrania"),
                new CountryTranslation(800, "es", true, "Uganda"),
                new CountryTranslation(858, "es", true, "Uruguay"),
                new CountryTranslation(860, "es", true, "Uzbekistán"),
                new CountryTranslation(548, "es", true, "Vanuatu"),
                new CountryTranslation(336, "es", true, "Vaticano, Ciudad del"),
                new CountryTranslation(862, "es", true, "Venezuela"),
                new CountryTranslation(704, "es", true, "Vietnam"),
                new CountryTranslation(876, "es", true, "Wallis y Futuna"),
                new CountryTranslation(887, "es", true, "Yemen"),
                new CountryTranslation(262, "es", true, "Yibuti"),
                new CountryTranslation(894, "es", true, "Zambia"),
                new CountryTranslation(716, "es", true, "Zimbabue"),

                // English
               new CountryTranslation(4  , "en", false, "Afghanistan"),
               new CountryTranslation(248, "en", false, "Åland Islands"),
               new CountryTranslation(8  , "en", false, "Albania"),
               new CountryTranslation(12 , "en", false, "Algeria"),
               new CountryTranslation(16 , "en", false, "American Samoa"),
               new CountryTranslation(20 , "en", false, "Andorra"),
               new CountryTranslation(24 , "en", false, "Angola"),
               new CountryTranslation(660, "en", false, "Anguilla"),
               new CountryTranslation(10 , "en", false, "Antarctica"),
               new CountryTranslation(28 , "en", false, "Antigua and Barbuda"),
               new CountryTranslation(32 , "en", false, "Argentina"),
               new CountryTranslation(51 , "en", false, "Armenia"),
               new CountryTranslation(533, "en", false, "Aruba"),
               new CountryTranslation(36 , "en", false, "Australia"),
               new CountryTranslation(40 , "en", false, "Austria"),
               new CountryTranslation(31 , "en", false, "Azerbaijan"),
               new CountryTranslation(44 , "en", false, "Bahamas"),
               new CountryTranslation(48 , "en", false, "Bahrain"),
               new CountryTranslation(50 , "en", false, "Bangladesh"),
               new CountryTranslation(52 , "en", false, "Barbados"),
               new CountryTranslation(112, "en", false, "Belarus"),
               new CountryTranslation(56 , "en", false, "Belgium"),
               new CountryTranslation(84 , "en", false, "Belize"),
               new CountryTranslation(204, "en", false, "Benin"),
               new CountryTranslation(60 , "en", false, "Bermuda"),
               new CountryTranslation(64 , "en", false, "Bhutan"),
               new CountryTranslation(68 , "en", false, "Bolivia (Plurinational State of)"),
               new CountryTranslation(535, "en", false, "Bonaire, Sint Eustatius and Saba"),
               new CountryTranslation(70 , "en", false, "Bosnia and Herzegovina"),
               new CountryTranslation(72 , "en", false, "Botswana"),
               new CountryTranslation(74 , "en", false, "Bouvet Island"),
               new CountryTranslation(76 , "en", false, "Brazil"),
               new CountryTranslation(86 , "en", false, "British Indian Ocean Territory"),
               new CountryTranslation(96 , "en", false, "Brunei Darussalam"),
               new CountryTranslation(100, "en", false, "Bulgaria"),
               new CountryTranslation(854, "en", false, "Burkina Faso"),
               new CountryTranslation(108, "en", false, "Burundi"),
               new CountryTranslation(132, "en", false, "Cabo Verde"),
               new CountryTranslation(116, "en", false, "Cambodia"),
               new CountryTranslation(120, "en", false, "Cameroon"),
               new CountryTranslation(124, "en", false, "Canada"),
               new CountryTranslation(136, "en", false, "Cayman Islands"),
               new CountryTranslation(140, "en", false, "Central African Republic"),
               new CountryTranslation(148, "en", false, "Chad"),
               new CountryTranslation(152, "en", false, "Chile"),
               new CountryTranslation(156, "en", false, "China"),
               new CountryTranslation(162, "en", false, "Christmas Island"),
               new CountryTranslation(166, "en", false, "Cocos (Keeling) Islands"),
               new CountryTranslation(170, "en", false, "Colombia"),
               new CountryTranslation(174, "en", false, "Comoros"),
               new CountryTranslation(178, "en", false, "Congo"),
               new CountryTranslation(180, "en", false, "Congo (Democratic Republic of the)"),
               new CountryTranslation(184, "en", false, "Cook Islands"),
               new CountryTranslation(188, "en", false, "Costa Rica"),
               new CountryTranslation(384, "en", false, "Côte d'Ivoire"),
               new CountryTranslation(191, "en", false, "Croatia"),
               new CountryTranslation(192, "en", false, "Cuba"),
               new CountryTranslation(531, "en", false, "Curaçao"),
               new CountryTranslation(196, "en", false, "Cyprus"),
               new CountryTranslation(203, "en", false, "Czech Republic"),
               new CountryTranslation(208, "en", false, "Denmark"),
               new CountryTranslation(262, "en", false, "Djibouti"),
               new CountryTranslation(212, "en", false, "Dominica"),
               new CountryTranslation(214, "en", false, "Dominican Republic"),
               new CountryTranslation(218, "en", false, "Ecuador"),
               new CountryTranslation(818, "en", false, "Egypt"),
               new CountryTranslation(222, "en", false, "El Salvador"),
               new CountryTranslation(226, "en", false, "Equatorial Guinea"),
               new CountryTranslation(232, "en", false, "Eritrea"),
               new CountryTranslation(233, "en", false, "Estonia"),
               new CountryTranslation(231, "en", false, "Ethiopia"),
               new CountryTranslation(238, "en", false, "Falkland Islands (Malvinas)"),
               new CountryTranslation(234, "en", false, "Faroe Islands"),
               new CountryTranslation(242, "en", false, "Fiji"),
               new CountryTranslation(246, "en", false, "Finland"),
               new CountryTranslation(250, "en", false, "France"),
               new CountryTranslation(254, "en", false, "French Guiana"),
               new CountryTranslation(258, "en", false, "French Polynesia"),
               new CountryTranslation(260, "en", false, "French Southern Territories"),
               new CountryTranslation(266, "en", false, "Gabon"),
               new CountryTranslation(270, "en", false, "Gambia"),
               new CountryTranslation(268, "en", false, "Georgia"),
               new CountryTranslation(276, "en", false, "Germany"),
               new CountryTranslation(288, "en", false, "Ghana"),
               new CountryTranslation(292, "en", false, "Gibraltar"),
               new CountryTranslation(300, "en", false, "Greece"),
               new CountryTranslation(304, "en", false, "Greenland"),
               new CountryTranslation(308, "en", false, "Grenada"),
               new CountryTranslation(312, "en", false, "Guadeloupe"),
               new CountryTranslation(316, "en", false, "Guam"),
               new CountryTranslation(320, "en", false, "Guatemala"),
               new CountryTranslation(831, "en", false, "Guernsey"),
               new CountryTranslation(324, "en", false, "Guinea"),
               new CountryTranslation(624, "en", false, "Guinea-Bissau"),
               new CountryTranslation(328, "en", false, "Guyana"),
               new CountryTranslation(332, "en", false, "Haiti"),
               new CountryTranslation(334, "en", false, "Heard Island and McDonald Islands"),
               new CountryTranslation(336, "en", false, "Holy See"),
               new CountryTranslation(340, "en", false, "Honduras"),
               new CountryTranslation(344, "en", false, "Hong Kong"),
               new CountryTranslation(348, "en", false, "Hungary"),
               new CountryTranslation(352, "en", false, "Iceland"),
               new CountryTranslation(356, "en", false, "India"),
               new CountryTranslation(360, "en", false, "Indonesia"),
               new CountryTranslation(364, "en", false, "Iran (Islamic Republic of)"),
               new CountryTranslation(368, "en", false, "Iraq"),
               new CountryTranslation(372, "en", false, "Ireland"),
               new CountryTranslation(833, "en", false, "Isle of Man"),
               new CountryTranslation(376, "en", false, "Israel"),
               new CountryTranslation(380, "en", false, "Italy"),
               new CountryTranslation(388, "en", false, "Jamaica"),
               new CountryTranslation(392, "en", false, "Japan"),
               new CountryTranslation(832, "en", false, "Jersey"),
               new CountryTranslation(400, "en", false, "Jordan"),
               new CountryTranslation(398, "en", false, "Kazakhstan"),
               new CountryTranslation(404, "en", false, "Kenya"),
               new CountryTranslation(296, "en", false, "Kiribati"),
               new CountryTranslation(408, "en", false, "Korea (Democratic People's Republic of)"),
               new CountryTranslation(410, "en", false, "Korea (Republic of)"),
               new CountryTranslation(414, "en", false, "Kuwait"),
               new CountryTranslation(417, "en", false, "Kyrgyzstan"),
               new CountryTranslation(418, "en", false, "Lao People's Democratic Republic"),
               new CountryTranslation(428, "en", false, "Latvia"),
               new CountryTranslation(422, "en", false, "Lebanon"),
               new CountryTranslation(426, "en", false, "Lesotho"),
               new CountryTranslation(430, "en", false, "Liberia"),
               new CountryTranslation(434, "en", false, "Libya"),
               new CountryTranslation(438, "en", false, "Liechtenstein"),
               new CountryTranslation(440, "en", false, "Lithuania"),
               new CountryTranslation(442, "en", false, "Luxembourg"),
               new CountryTranslation(446, "en", false, "Macao"),
               new CountryTranslation(807, "en", false, "Macedonia (the former Yugoslav Republic of)"),
               new CountryTranslation(450, "en", false, "Madagascar"),
               new CountryTranslation(454, "en", false, "Malawi"),
               new CountryTranslation(458, "en", false, "Malaysia"),
               new CountryTranslation(462, "en", false, "Maldives"),
               new CountryTranslation(466, "en", false, "Mali"),
               new CountryTranslation(470, "en", false, "Malta"),
               new CountryTranslation(584, "en", false, "Marshall Islands"),
               new CountryTranslation(474, "en", false, "Martinique"),
               new CountryTranslation(478, "en", false, "Mauritania"),
               new CountryTranslation(480, "en", false, "Mauritius"),
               new CountryTranslation(175, "en", false, "Mayotte"),
               new CountryTranslation(484, "en", false, "Mexico"),
               new CountryTranslation(583, "en", false, "Micronesia (Federated States of)"),
               new CountryTranslation(498, "en", false, "Moldova (Republic of)"),
               new CountryTranslation(492, "en", false, "Monaco"),
               new CountryTranslation(496, "en", false, "Mongolia"),
               new CountryTranslation(499, "en", false, "Montenegro"),
               new CountryTranslation(500, "en", false, "Montserrat"),
               new CountryTranslation(504, "en", false, "Morocco"),
               new CountryTranslation(508, "en", false, "Mozambique"),
               new CountryTranslation(104, "en", false, "Myanmar"),
               new CountryTranslation(516, "en", false, "Namibia"),
               new CountryTranslation(520, "en", false, "Nauru"),
               new CountryTranslation(524, "en", false, "Nepal"),
               new CountryTranslation(528, "en", false, "Netherlands"),
               new CountryTranslation(540, "en", false, "New Caledonia"),
               new CountryTranslation(554, "en", false, "New Zealand"),
               new CountryTranslation(558, "en", false, "Nicaragua"),
               new CountryTranslation(562, "en", false, "Niger"),
               new CountryTranslation(566, "en", false, "Nigeria"),
               new CountryTranslation(570, "en", false, "Niue"),
               new CountryTranslation(574, "en", false, "Norfolk Island"),
               new CountryTranslation(580, "en", false, "Northern Mariana Islands"),
               new CountryTranslation(578, "en", false, "Norway"),
               new CountryTranslation(512, "en", false, "Oman"),
               new CountryTranslation(586, "en", false, "Pakistan"),
               new CountryTranslation(585, "en", false, "Palau"),
               new CountryTranslation(275, "en", false, "Palestine, State of"),
               new CountryTranslation(591, "en", false, "Panama"),
               new CountryTranslation(598, "en", false, "Papua New Guinea"),
               new CountryTranslation(600, "en", false, "Paraguay"),
               new CountryTranslation(604, "en", false, "Peru"),
               new CountryTranslation(608, "en", false, "Philippines"),
               new CountryTranslation(612, "en", false, "Pitcairn"),
               new CountryTranslation(616, "en", false, "Poland"),
               new CountryTranslation(620, "en", false, "Portugal"),
               new CountryTranslation(630, "en", false, "Puerto Rico"),
               new CountryTranslation(634, "en", false, "Qatar"),
               new CountryTranslation(638, "en", false, "Réunion"),
               new CountryTranslation(642, "en", false, "Romania"),
               new CountryTranslation(643, "en", false, "Russian Federation"),
               new CountryTranslation(646, "en", false, "Rwanda"),
               new CountryTranslation(652, "en", false, "Saint Barthélemy"),
               new CountryTranslation(654, "en", false, "Saint Helena, Ascension and Tristan da Cunha"),
               new CountryTranslation(659, "en", false, "Saint Kitts and Nevis"),
               new CountryTranslation(662, "en", false, "Saint Lucia"),
               new CountryTranslation(663, "en", false, "Saint Martin (French part)"),
               new CountryTranslation(666, "en", false, "Saint Pierre and Miquelon"),
               new CountryTranslation(670, "en", false, "Saint Vincent and the Grenadines"),
               new CountryTranslation(882, "en", false, "Samoa"),
               new CountryTranslation(674, "en", false, "San Marino"),
               new CountryTranslation(678, "en", false, "Sao Tome and Principe"),
               new CountryTranslation(682, "en", false, "Saudi Arabia"),
               new CountryTranslation(686, "en", false, "Senegal"),
               new CountryTranslation(688, "en", false, "Serbia"),
               new CountryTranslation(690, "en", false, "Seychelles"),
               new CountryTranslation(694, "en", false, "Sierra Leone"),
               new CountryTranslation(702, "en", false, "Singapore"),
               new CountryTranslation(534, "en", false, "Sint Maarten (Dutch part)"),
               new CountryTranslation(703, "en", false, "Slovakia"),
               new CountryTranslation(705, "en", false, "Slovenia"),
               new CountryTranslation(90 , "en", false, "Solomon Islands"),
               new CountryTranslation(706, "en", false, "Somalia"),
               new CountryTranslation(710, "en", false, "South Africa"),
               new CountryTranslation(239, "en", false, "South Georgia and the South Sandwich Islands"),
               new CountryTranslation(728, "en", false, "South Sudan"),
               new CountryTranslation(724, "en", false, "Spain"),
               new CountryTranslation(144, "en", false, "Sri Lanka"),
               new CountryTranslation(729, "en", false, "Sudan"),
               new CountryTranslation(740, "en", false, "Suriname"),
               new CountryTranslation(744, "en", false, "Svalbard and Jan Mayen"),
               new CountryTranslation(748, "en", false, "Swaziland"),
               new CountryTranslation(752, "en", false, "Sweden"),
               new CountryTranslation(756, "en", false, "Switzerland"),
               new CountryTranslation(760, "en", false, "Syrian Arab Republic"),
               new CountryTranslation(158, "en", false, "Taiwan, Province of China[a]"),
               new CountryTranslation(762, "en", false, "Tajikistan"),
               new CountryTranslation(834, "en", false, "Tanzania, United Republic of"),
               new CountryTranslation(764, "en", false, "Thailand"),
               new CountryTranslation(626, "en", false, "Timor-Leste"),
               new CountryTranslation(768, "en", false, "Togo"),
               new CountryTranslation(772, "en", false, "Tokelau"),
               new CountryTranslation(776, "en", false, "Tonga"),
               new CountryTranslation(780, "en", false, "Trinidad and Tobago"),
               new CountryTranslation(788, "en", false, "Tunisia"),
               new CountryTranslation(792, "en", false, "Turkey"),
               new CountryTranslation(795, "en", false, "Turkmenistan"),
               new CountryTranslation(796, "en", false, "Turks and Caicos Islands"),
               new CountryTranslation(798, "en", false, "Tuvalu"),
               new CountryTranslation(800, "en", false, "Uganda"),
               new CountryTranslation(804, "en", false, "Ukraine"),
               new CountryTranslation(784, "en", false, "United Arab Emirates"),
               new CountryTranslation(826, "en", false, "United Kingdom of Great Britain and Northern Ireland"),
               new CountryTranslation(840, "en", false, "United States of America"),
               new CountryTranslation(581, "en", false, "United States Minor Outlying Islands"),
               new CountryTranslation(858, "en", false, "Uruguay"),
               new CountryTranslation(860, "en", false, "Uzbekistan"),
               new CountryTranslation(548, "en", false, "Vanuatu"),
               new CountryTranslation(862, "en", false, "Venezuela (Bolivarian Republic of)"),
               new CountryTranslation(704, "en", false, "Viet Nam"),
               new CountryTranslation(92 , "en", false, "Virgin Islands (British)"),
               new CountryTranslation(850, "en", false, "Virgin Islands (U.S.)"),
               new CountryTranslation(876, "en", false, "Wallis and Futuna"),
               new CountryTranslation(732, "en", false, "Western Sahara"),
               new CountryTranslation(887, "en", false, "Yemen"),
               new CountryTranslation(894, "en", false, "Zambia"),
               new CountryTranslation(716, "en", false, "Zimbabwe")
            };
        }

        public static AreaType[] GetAreaTypes()
        {
            return new[]
            {
                new AreaType(1),
                new AreaType(2),
                new AreaType(3),
                new AreaType(4),
            };
        }

        public static AreaTypeTranslation[] GetAreaTypeTranslations()
        {
            return new[]
            {
                // Spanish
                new AreaTypeTranslation(1, "es", true, "Picking"),
                new AreaTypeTranslation(2, "es", true, "Picking (volumen)"),
                new AreaTypeTranslation(3, "es", true, "Irregular"),
                new AreaTypeTranslation(4, "es", true, "Temporal"),

                // English
                new AreaTypeTranslation(1, "en", false, "Picking"),
                new AreaTypeTranslation(2, "en", false, "Picking (volume)"),
                new AreaTypeTranslation(3, "en", false, "Irregular"),
                new AreaTypeTranslation(4, "en", false, "Temporal"),
            };
        }

        public static Menu[] GetMenus()
        {
            var principalMenus = new Menu[]
           {
                new Menu {Code = MenusSeed.Procceses,Order = 1, MustHaveClient = false, Url = "/processes", ImageClass = "fa-tasks"},
                new Menu {Code = MenusSeed.Operations, Order = 2, MustHaveClient = false, Url = "/operations", ImageClass = "fa-cube "},
                new Menu {Code = MenusSeed.Masters, Order = 3, MustHaveClient = false, Url = "/masters", ImageClass = "fa-database"},
                new Menu {Code = MenusSeed.Administration, Order = 4, MustHaveClient = false, Url = "/administration", ImageClass = "fa-dashboard" },
                new Menu {Code = MenusSeed.Planification, Order = 5, MustHaveClient = false, Url = "/planification", ImageClass = "fa-calendar-o"},
           };

            var principalMenuDictionary = principalMenus.ToDictionary(x => x.Code);

            var menus = new Menu[]
            {
                // Procesos:
                new Menu
                {
                    Code = MenusSeed.Inbounds,
                    Order = 10,
                    MustHaveClient = false,
                    ParentMenu = principalMenuDictionary[MenusSeed.Procceses]
                },
                new Menu
                {
                    Code = MenusSeed.StockManagement,
                    Order = 20,
                    MustHaveClient = false,
                    ParentMenu = principalMenuDictionary[MenusSeed.Procceses]
                },
                new Menu
                {
                    Code = MenusSeed.Picking,
                    Order = 30,
                    MustHaveClient = false,
                    ParentMenu = principalMenuDictionary[MenusSeed.Procceses]
                },
                new Menu
                {
                    Code = MenusSeed.Expeditions,
                    Order = 40,
                    MustHaveClient = false,
                    ParentMenu = principalMenuDictionary[MenusSeed.Procceses]
                },
                //Administración:
                new Menu
                {
                    Code = MenusSeed.WarehousesManagement,
                    Order = 10,
                    MustHaveClient = false,
                    ParentMenu = principalMenuDictionary[MenusSeed.Administration],
                    ImageClass = "fa-cubes"
                },
                new Menu
                {
                    Code = MenusSeed.ClientsManagement,
                    Order = 20,
                    MustHaveClient = false,
                    ParentMenu = principalMenuDictionary[MenusSeed.Administration],
                    ImageClass = "fa-user-md"
                },
                new Menu
                {
                    Code = MenusSeed.CompaniesManagement,
                    Order = 30,
                    MustHaveClient = false,
                    ParentMenu = principalMenuDictionary[MenusSeed.Administration],
                    ImageClass = "fa-suitcase"
                },
                new Menu
                {
                    Code = MenusSeed.WorkstationsManagement,
                    Order = 40,
                    MustHaveClient = false,
                    ParentMenu = principalMenuDictionary[MenusSeed.Administration],
                    ImageClass = "fa-desktop "
                },
                new Menu
                {
                    Code = MenusSeed.UsersManagement,
                    Order = 50,
                    MustHaveClient = false,
                    ParentMenu = principalMenuDictionary[MenusSeed.Administration],
                    ImageClass = "fa-users"
                },
                // Maestros del cliente:
                new Menu
                {
                    Code = ClientActions.Addressees,
                    Order = 10,
                    MustHaveClient = true,
                    Url = "/masters/addressees",
                    ParentMenu = principalMenuDictionary[MenusSeed.Masters],
                    ImageClass = "fa-mail-forward"
                },
                new Menu
                {
                    Code = ClientActions.Items,
                    Order = 20,
                    MustHaveClient = true,
                    Url = "/masters/items",
                    ParentMenu = principalMenuDictionary[MenusSeed.Masters],
                    ImageClass = "fa-cube"
                },
                new Menu
                {
                    Code = ClientActions.Families,
                    Order = 30,
                    MustHaveClient = true,
                    Url = "/masters/families",
                    ParentMenu = principalMenuDictionary[MenusSeed.Masters],
                    ImageClass = "fa-object-group"
                }
            };

            var menuDictionary = menus.ToDictionary(x => x.Code);

            var submenus = new Menu[]
            {
                 //Gestión de almacenes:
                new Menu
                {
                    Code = MenusSeed.Areas,
                    Order = 10,
                    MustHaveClient = false,
                    Url = "/administration/warehouse-management/areas",
                    ParentMenu = menuDictionary[MenusSeed.WarehousesManagement]
                },
                new Menu
                {
                    Code = MenusSeed.BinLocations,
                    Order = 20,
                    MustHaveClient = false,
                    Url = "/administration/warehouse-management/bin-locations",
                    ParentMenu = menuDictionary[MenusSeed.WarehousesManagement]
                },new Menu
                {
                    Code = MenusSeed.PackingTypes,
                    Order = 30,
                    MustHaveClient = false,
                    Url = "/administration/warehouse-management/packing-types",
                    ParentMenu = menuDictionary[MenusSeed.WarehousesManagement]
                },
                new Menu
                {
                    Code = MenusSeed.SorterTypes,
                    Order = 40,
                    MustHaveClient = false,
                    Url = "/administration/warehouse-management/sorter-types",
                    ParentMenu = menuDictionary[MenusSeed.WarehousesManagement]
                },
                // Gestión de empresas
                new Menu
                {
                    Code = MenusSeed.Companies,
                    Order = 10,
                    MustHaveClient = false,
                    Url = "/administration/companies-management/companies",
                    ParentMenu = menuDictionary[MenusSeed.CompaniesManagement]
                },
                // Gestión de clientes
                new Menu
                {
                    Code = MenusSeed.Clients,
                    Order = 10,
                    MustHaveClient = false,
                    Url = "/administration/clients-management/clients",
                    ParentMenu = menuDictionary[MenusSeed.ClientsManagement]
                },
                // Gestión de puestos
                new Menu
                {
                    Code = MenusSeed.Workstations,
                    Order = 10,
                    MustHaveClient = false,
                    Url = "/administration/workstations-management/workstations",
                    ParentMenu = menuDictionary[MenusSeed.WorkstationsManagement]
                },
                // Gestión de usuarios
                new Menu
                {
                    Code = MenusSeed.Users,
                    Order = 10,
                    MustHaveClient = false,
                    Url = "/administration/users-management/users",
                    ParentMenu = menuDictionary[MenusSeed.UsersManagement]
                },
                // Entradas
                new Menu
                {
                    Code = MenusSeed.InboundsManagement,
                    Order = 10,
                    MustHaveClient = true,
                    Url = "/processes/inbounds/inbounds-management",
                    ParentMenu = menuDictionary[MenusSeed.Inbounds]
                },
            };

            var allmenus = new List<Menu>();
            allmenus.AddRange(principalMenus);
            allmenus.AddRange(menus);
            allmenus.AddRange(submenus);
            return allmenus.ToArray();
        }

        public static MenuTranslation[] GetMenuTranslations()
        {
            return new MenuTranslation[]
            {
                // Spanish
                new MenuTranslation(MenusSeed.Procceses, "es", true, "Procesos"),
                new MenuTranslation(MenusSeed.Operations, "es", true, "Operaciones"),
                new MenuTranslation(MenusSeed.Masters, "es", true, "Maestros"),
                new MenuTranslation(MenusSeed.Administration, "es", true, "Administración"),
                new MenuTranslation(MenusSeed.Planification, "es", true, "Planificación"),
                ////----
                new MenuTranslation(MenusSeed.WarehousesManagement, "es", true, "Gestión de almacenes"),
                new MenuTranslation(MenusSeed.ClientsManagement, "es", true, "Gestión de clientes"),
                new MenuTranslation(MenusSeed.CompaniesManagement, "es", true, "Gestión de empresas"),
                new MenuTranslation(MenusSeed.WorkstationsManagement, "es", true, "Gestión de puestos"),
                new MenuTranslation(MenusSeed.UsersManagement, "es", true, "Gestión de usuarios"),
                new MenuTranslation(MenusSeed.Inbounds, "es", true, "Entradas"),
                new MenuTranslation(MenusSeed.StockManagement, "es", true, "Gestión de stock"),
                new MenuTranslation(MenusSeed.Picking, "es", true, "Picking"),
                new MenuTranslation(MenusSeed.Expeditions, "es", true, "Expediciones"),
                ////----
                new MenuTranslation(MenusSeed.Areas, "es", true, "Áreas"),
                new MenuTranslation(MenusSeed.BinLocations, "es", true, "Huecos"),
                new MenuTranslation(MenusSeed.PackingTypes, "es", true, "Tipos de packing"),
                new MenuTranslation(MenusSeed.SorterTypes, "es", true, "Tipos de sorter"),
                new MenuTranslation(MenusSeed.Companies, "es", true, "Empresas"),
                new MenuTranslation(MenusSeed.Clients, "es", true, "Clientes"),
                new MenuTranslation(ClientActions.Addressees, "es", true, "Destinatarios"),
                new MenuTranslation(ClientActions.Items, "es", true, "Items"),
                new MenuTranslation(ClientActions.Families, "es", true, "Familias"),
                new MenuTranslation(MenusSeed.Workstations, "es", true, "Puestos"),
                new MenuTranslation(MenusSeed.Users, "es", true, "Usuarios"),
                new MenuTranslation(MenusSeed.InboundsManagement, "es", true, "Gestión de entradas"),

                //// English
                new MenuTranslation(MenusSeed.Procceses, "en", false, "Procceses"),
                new MenuTranslation(MenusSeed.Operations, "en", false, "Operations"),
                new MenuTranslation(MenusSeed.Masters, "en", false, "Masters"),
                new MenuTranslation(MenusSeed.Administration, "en", false, "Administration"),
                new MenuTranslation(MenusSeed.Planification, "en", false, "Planification"),
                ////----
                new MenuTranslation(MenusSeed.WarehousesManagement, "en", false, "Warehouses management"),
                new MenuTranslation(MenusSeed.ClientsManagement, "en", false, "Clients management"),
                new MenuTranslation(MenusSeed.CompaniesManagement, "en", false, "Companies management"),
                new MenuTranslation(MenusSeed.WorkstationsManagement, "en", false, "Workstations management"),
                new MenuTranslation(MenusSeed.UsersManagement, "en", false, "Users management"),
                new MenuTranslation(MenusSeed.Inbounds, "en", false, "Inbounds"),
                new MenuTranslation(MenusSeed.StockManagement, "en", false, "StockManagement"),
                new MenuTranslation(MenusSeed.Picking, "en", false, "Picking"),
                new MenuTranslation(MenusSeed.Expeditions, "en", false, "Expeditions"),
                ////----
                new MenuTranslation(MenusSeed.Areas, "en", false, "Areas"),
                new MenuTranslation(MenusSeed.BinLocations, "en", false, "Bin locations"),
                new MenuTranslation(MenusSeed.PackingTypes, "en", false, "Packing types"),
                new MenuTranslation(MenusSeed.SorterTypes, "en", false, "Sorter types"),
                new MenuTranslation(MenusSeed.Companies, "en", false, "Companies"),
                new MenuTranslation(MenusSeed.Clients, "en", false, "Clients"),
                new MenuTranslation(ClientActions.Addressees, "en", false, "Addressees"),
                new MenuTranslation(ClientActions.Items, "en", false, "Items"),
                new MenuTranslation(ClientActions.Families, "en", false, "Families"),
                new MenuTranslation(MenusSeed.Workstations, "en", false, "Workstations"),
                new MenuTranslation(MenusSeed.Users, "en", false, "Users"),
                new MenuTranslation(MenusSeed.InboundsManagement, "en", false, "InboundsManagement"),
            };
        }

        public static ItemType[] GetItemypes()
        {
            return new[]
            {
                new ItemType(1),
                new ItemType(2),
                new ItemType(3),
            };
        }

        public static ItemTypeTranslation[] GetItemTypeTranslations()
        {
            return new[]
            {
                // Spanish
                new ItemTypeTranslation(1, "es", true, "Artículo"),
                new ItemTypeTranslation(2, "es", true, "Pack"),
                new ItemTypeTranslation(3, "es", true, "Multipack"),

                // English
                new ItemTypeTranslation(1, "en", false, "Article"),
                new ItemTypeTranslation(2, "en", false, "Pack"),
                new ItemTypeTranslation(3, "en", false, "Multipack"),
            };
        }
    }
}
